with Ada.Command_Line;
with Ada.Directories;
with Ada.Text_IO;
with GNAT.OS_Lib;
with Project_Tools.Processes;

package body Crossing is

   LF : constant Character := Character'Val (10);

   --  The Python program, line by line. It is what it is because jinja2 is
   --  what it is; nothing in it decides anything about this engine.
   Harness : constant String :=
        "import sys, os, json, subprocess, difflib, datetime, tempfile"
      & LF & "try:"
      & LF & "    import jinja2"
      & LF & "except ImportError:"
      & LF & "    print(""cross: skipped, python3 has no jinja2"")"
      & LF & "    sys.exit(0)"
      & LF & ""
      & LF & "def option(name, default=None):"
      & LF & "    a = sys.argv"
      & LF & "    return a[a.index(name) + 1] if name in a and a.index(name) "
      & "+ 1 < len(a) else default"
      & LF & "binary = option(""--binary"")"
      & LF & "model = option(""--model"")"
      & LF & "template = option(""--template"")"
      & LF & "fmt = option(""--format"")"
      & LF & "think = ""think"" if ""--think"" in sys.argv else (""no-think"""
      & " if ""--no-think"" in sys.argv else None)"
      & LF & "expressions = ""--expressions"" in sys.argv"
      & LF & "without_tools = ""--without-tools"" in sys.argv"
      & LF & "without_reasoning = ""--without-reasoning"" in sys.argv"
      & LF & "if not model or not binary:"
      & LF & "    print(""cross: --model PATH is required"")"
      & LF & "    sys.exit(1)"
      & LF & ""
      & LF & "def own_tokens():"
      & LF & "    r = subprocess.run([binary, ""render"", ""--model"", model,"
      & " ""--show-tokens""], capture_output=True, text=True)"
      & LF & "    lines = r.stdout.split(""\n"") if r.returncode == 0 else ["
      & """"", """"]"
      & LF & "    return lines[0], lines[1]"
      & LF & ""
      & LF & "def own_template():"
      & LF & "    r = subprocess.run([binary, ""render"", ""--model"", model,"
      & " ""--show-template""], capture_output=True, text=True)"
      & LF & "    if r.returncode != 0:"
      & LF & "        print(""cross: the model's template would not read: "" "
      & "+ r.stderr.strip())"
      & LF & "        sys.exit(1)"
      & LF & "    return r.stdout"
      & LF & ""
      & LF & "if template:"
      & LF & "    source = open(template).read()"
      & LF & "    if source.endswith(""\n""):"
      & LF & "        source = source[:-1]"
      & LF & "else:"
      & LF & "    source = own_template()"
      & LF & "    if not template and not fmt:"
      & LF & "        template_file = tempfile.NamedTemporaryFile(""w"", suff"
      & "ix="".jinja"", delete=False)"
      & LF & "        template_file.write(source)"
      & LF & "        template_file.close()"
      & LF & "        template = template_file.name"
      & LF & ""
      & LF & "env = jinja2.Environment(trim_blocks=True, lstrip_blocks=True, "
      & "extensions=[""jinja2.ext.loopcontrols""])"
      & LF & "def tojson(value, **keywords):"
      & LF & "    keywords.pop(""ensure_ascii"", None)"
      & LF & "    return json.dumps(value, ensure_ascii=False, **keywords)"
      & LF & "env.filters[""tojson""] = tojson"
      & LF & "env.globals[""strftime_now""] = lambda f: datetime.datetime.now"
      & "().strftime(f)"
      & LF & "def refuse(message):"
      & LF & "    raise Exception(message)"
      & LF & "env.globals[""raise_exception""] = refuse"
      & LF & "tmpl = env.from_string(source)"
      & LF & "bos_token, eos_token = own_tokens()"
      & LF & ""
      & LF & "tools = ["
      & LF & " {""type"": ""function"", ""function"": {""name"": ""calc"", """
      & "description"": "" Evaluate a binary arithmetic operation. "","
      & LF & "  ""parameters"": {""type"": ""object"", ""properties"": {"
      & LF & "    ""a"": {""type"": ""integer"", ""description"": ""left oper"
      & "and""},"
      & LF & "    ""op"": {""type"": ""string"", ""enum"": [""+"", ""-"", ""*"
      & """, ""/""], ""description"": ""the operator""},"
      & LF & "    ""b"": {""type"": ""integer""},"
      & LF & "    ""exact"": {""type"": ""boolean"", ""default"": False, ""mi"
      & "nimum"": 0},"
      & LF & "    ""tags"": {""type"": ""array"", ""items"": {""type"": ""str"
      & "ing""}}},"
      & LF & "   ""required"": [""a"", ""op"", ""b""]}, ""return"": {""type"""
      & ": ""number""}}},"
      & LF & " {""type"": ""function"", ""function"": {""name"": ""weather"","
      & " ""description"": ""Look up the weather."","
      & LF & "  ""parameters"": {""type"": ""object"", ""properties"": {"
      & LF & "    ""city"": {""type"": ""string"", ""description"": ""which c"
      & "ity"", ""enum"": [""Aarhus"", ""Odense""], ""required"": [""cit"
      & "y""]}}}}}]"
      & LF & ""
      & LF & "def call(name, arguments):"
      & LF & "    return {""function"": {""name"": name, ""arguments"": argum"
      & "ents}}"
      & LF & "conversations = ["
      & LF & " (""plain"", [{""role"": ""user"", ""content"": ""hi""}], True,"
      & " False),"
      & LF & " (""system and user"", [{""role"": ""system"", ""content"": ""B"
      & "e brief.""}, {""role"": ""user"", ""content"": ""hi""}], True, "
      & "False),"
      & LF & " (""tools, no system"", [{""role"": ""user"", ""content"": ""ad"
      & "d 2 and 3""}], True, True),"
      & LF & " (""tools with system"", [{""role"": ""system"", ""content"": "
      & """Be brief.""}, {""role"": ""user"", ""content"": ""add""}], Tr"
      & "ue, True),"
      & LF & " (""call turn with text"", [{""role"": ""user"", ""content"": "
      & """add""},"
      & LF & "   {""role"": ""assistant"", ""content"": ""  Let me compute.  "
      & """, ""tool_calls"": [call(""calc"", {""a"": 2, ""op"": ""+"", "
      & """b"": 3})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""5""}, {""role"": ""tool"
      & """, ""content"": ""5 again""}, {""role"": ""user"", ""content"""
      & ": ""thanks""}], True, True),"
      & LF & " (""call turn without text"", [{""role"": ""user"", ""content"""
      & ": ""add""},"
      & LF & "   {""role"": ""assistant"", ""content"": """", ""tool_calls"":"
      & " [call(""calc"", {""a"": 2, ""op"": ""*"", ""b"": 3, ""exact"":"
      & " True})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""6""}], True, True),"
      & LF & " (""two calls"", [{""role"": ""user"", ""content"": ""add""},"
      & LF & "   {""role"": ""assistant"", ""content"": """", ""tool_calls"":"
      & " [call(""calc"", {""a"": 1, ""op"": ""+"", ""b"": 1}), call(""w"
      & "eather"", {""city"": ""Odense""})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""2""}, {""role"": ""tool"
      & """, ""content"": ""rain""}, {""role"": ""assistant"", ""content"
      & """: ""done""}], False, True),"
      & LF & " (""reply, no generation prompt"", [{""role"": ""user"", ""cont"
      & "ent"": ""hi""}, {""role"": ""assistant"", ""content"": ""yo""}]"
      & ", False, False),"
      & LF & " (""reasoning kept and dropped"", [{""role"": ""user"", ""conte"
      & "nt"": ""q1""}, {""role"": ""assistant"", ""content"": ""<think>"
      & "\nfirst\n</think>\n\nA1""},"
      & LF & "   {""role"": ""user"", ""content"": ""q2""}, {""role"": ""assi"
      & "stant"", ""content"": ""<think>\nsecond\n</think>\n\nA2""}], Tr"
      & "ue, False),"
      & LF & "]"
      & LF & "expression_messages = [{""role"": ""system"", ""content"": ""s"
      & """}, {""role"": ""user"", ""content"": ""hi""}, {""role"": ""as"
      & "sistant"", ""content"": ""yo""}, {""role"": ""user"", ""content"
      & """: ""again""}]"
      & LF & "expression_suites = ["
      & LF & " ""{% set l = ['b', 'a', 'c', 'a'] %}{{ l | join(', ') }}|{{ l "
      & "| sort | join }}|{{ l | sort(reverse=true) | join }}|{{ l | uni"
      & "que | join }}|{{ [3, 1, 2] | sort | join('-') }}|{{ l | select("
      & "'equalto', 'a') | list | length }}|{{ l | reject('equalto', 'a'"
      & ") | join }}|{{ 'abc' | list | join('.') }}"","
      & LF & " ""{{ messages | map(attribute='role') | join(',') }}|{{ messag"
      & "es | selectattr('role', 'equalto', 'user') | map(attribute='con"
      & "tent') | join('+') }}|{{ messages | rejectattr('role', 'equalto"
      & "', 'user') | list | length }}|{{ (messages | first).role }}|{{ "
      & "(messages | last)['content'] }}"","
      & LF & " ""{{ 'a\\nb\\n\\nc' | indent(2) }}|{{ 'a\\nb' | indent(width=1"
      & ", first=True) }}|{{ 'a\\n\\nb' | indent(3, blank=True) }}"","
      & LF & " ""{% set d = {'a': 1, 'b': 'x', 'c': [1, 2], 'd': {'e': true}}"
      & " %}{{ d }}|{{ d | tojson }}|{{ d.a + 1 }}|{{ d.keys() | join(',"
      & "') }}|{{ d.values() | length }}|{{ d.get('b') }}{{ d.get('zz', "
      & "'none') }}|{% for k, v in d | dictsort %}{{ k }}={{ v }};{% end"
      & "for %}|{{ d.d.e }}|{{ {'x': messages[0].role} | tojson }}|{{ d "
      & "| tojson(indent=2) }}"","
      & LF & " ""{% set m = {'z': 1, 'a': 2} %}{% for k, v in m.items() %}{{ "
      & "k }}{% endfor %}{% for k, v in m | dictsort %}{{ k }}{% endfor "
      & "%}{% for k, v in m | dictsort(by='value', reverse=true) %}{{ k "
      & "}}{% endfor %}{% if 'a' in m.keys() %}y{% endif %}{% for a, b i"
      & "n [[1, 2], [3, 4]] %}{{ a + b }}{% endfor %}"","
      & LF & " ""{% for i in range(5) %}{% if i == 1 %}{% continue %}{% endif"
      & " %}{% if i == 3 %}{% break %}{% endif %}{{ i }}{% endfor %}|{% "
      & "for m in messages %}{{ loop.length }}{{ loop.revindex }}{{ loop"
      & ".revindex0 }}{% endfor %}|{% filter upper %}ab{{ 'c' }}{% endfi"
      & "lter %}|{% for i in range(2, 9, 3) %}{{ loop.length }}{{ loop.r"
      & "evindex }}{% endfor %}"","
      & LF & " ""{% macro box(title) %}<{{ title }}>{{ caller() }}</{{ title "
      & "}}>{% endmacro %}{% call box('b') %}inner {{ 1 + 1 }}{% endcall"
      & " %}|{% set t = 'x' %}{% call box(t) %}{% call box('n') %}deep{%"
      & " endcall %}{% endcall %}|{% macro two(t) %}[{{ caller(1, 'z') }"
      & "}]{% endmacro %}{% call(n, s) two('q') %}{{ n + 1 }}{{ s }}{% e"
      & "ndcall %}"","
      & LF & " ""{% set i = 1 %}{{ i + 1 }}{% set j = i %}{{ j + i }}{% set t"
      & " = '1' %}{{ t + '1' }}{{ t ~ i }}{% if i == '1' %}!{% endif %}{"
      & "% if i == 1 %}y{% endif %}{% if t == '1' %}z{% endif %}{% if i "
      & "is number and t is not number %}n{% endif %}{% if i is string %"
      & "}!{% endif %}{% if (i | string) is string %}s{% endif %}{{ mess"
      & "ages | length + 1 }}{{ '7' | int + 1 }}{{ 'x' ~ 1 + 2 ~ 'y' }}"
      & ""","
      & LF & " ""[{{ 1 == 1 }}][{{ nothing is defined }}][{{ true }}][{{ fals"
      & "e }}][{{ none }}][{{ 'ab'.startswith('a') }}]{% set ok = 1 == 2"
      & " %}{{ ok }}{{ ok | tojson }}{% if (1 == 1) != (2 == 3) %}y{% en"
      & "dif %}{% for m in messages %}{{ m.role + ('!' if loop.first els"
      & "e '') }}{% endfor %}"","
      & LF & " ""{% set l = [['b', 'c'], 'd'] %}{{ l[0][1] }}{{ l[1][0] }}{{ "
      & "messages[0].role[0] }}{{ messages[0]['content'][0] }}{{ 'a|b'.s"
      & "plit('|')[1].upper() }}{{ (messages | selectattr('role', 'equal"
      & "to', 'user') | list)[0].content }}"","
      & LF & " ""{{ messages | selectattr('role', 'equalto', 'assistant') | m"
      & "ap(attribute='content') | list | tojson }}|{{ messages | map(at"
      & "tribute='role') | unique | list | length }}|{{ messages | rejec"
      & "tattr('role', 'equalto', 'system') | map(attribute='role') | jo"
      & "in('/') }}|{{ messages | selectattr('role', 'in', ['user', 'sys"
      & "tem']) | list | length }}|{{ messages | select('mapping') | lis"
      & "t | length }}|{{ messages | map(attribute='content') | select('"
      & "equalto', 'yo') | join }}"","
      & LF & " ""{{ [1, 2, 3] | select('number') | join(',') }}|{{ ['a', none"
      & ", 'b'] | select('defined') | list | length }}|{{ ['a', none, 'b"
      & "'] | reject('none') | join }}|{{ [3, 1, 2] | sort(reverse=True)"
      & " | first }}|{{ ['B', 'a', 'C'] | sort | join }}|{{ ['B', 'a', '"
      & "C'] | sort(case_sensitive=True) | join }}|{% for m in messages["
      & "1:] %}{{ m.role[0] }}{% endfor %}{% for m in messages[:2] %}{{ "
      & "m.role[0] }}{% endfor %}|{{ (messages[0].nothing or 'd') }}{{ ("
      & "messages[0].role and 'a') }}|{% if 'role' in messages[0] and 'x"
      & "' not in {'a': 1} %}m{% endif %}"","
      & LF & "]"
      & LF & ""
      & LF & "def render_ours(messages, add_generation, use_tools, source_arg"
      & "s):"
      & LF & "    args = [binary, ""render"", ""--model"", model] + source_ar"
      & "gs"
      & LF & "    for m in messages:"
      & LF & "        if m[""role""] == ""system"":"
      & LF & "            args += [""--system"", m[""content""]]"
      & LF & "        elif m[""role""] == ""user"":"
      & LF & "            args += [""--prompt"", m[""content""]]"
      & LF & "        elif m[""role""] == ""assistant"":"
      & LF & "            args += [""--assistant"", m.get(""content"", """")]"
      & LF & "            for c in m.get(""tool_calls"", []):"
      & LF & "                args += [""--calls"", json.dumps({""name"": c["
      & """function""][""name""], ""arguments"": c[""function""][""argum"
      & "ents""]}, ensure_ascii=False)]"
      & LF & "        elif m[""role""] == ""tool"":"
      & LF & "            args += [""--tool"", m[""content""]]"
      & LF & "    if use_tools:"
      & LF & "        args += [""--tools"", json.dumps(tools, ensure_ascii=Fa"
      & "lse)]"
      & LF & "    if add_generation:"
      & LF & "        args += [""--generation-prompt""]"
      & LF & "    if think == ""think"":"
      & LF & "        args += [""--think""]"
      & LF & "    if think == ""no-think"":"
      & LF & "        args += [""--no-think""]"
      & LF & "    r = subprocess.run(args, capture_output=True, text=True)"
      & LF & "    return r.stdout if r.returncode == 0 else ""REFUSED "" + r."
      & "stderr.strip()"
      & LF & ""
      & LF & "def render_theirs(compiled, messages, add_generation, use_tools"
      & "):"
      & LF & "    context = dict(messages=messages, add_generation_prompt=add"
      & "_generation, bos_token=bos_token, eos_token=eos_token)"
      & LF & "    if use_tools:"
      & LF & "        context[""tools""] = tools"
      & LF & "    if think == ""think"":"
      & LF & "        context[""enable_thinking""] = True"
      & LF & "    if think == ""no-think"":"
      & LF & "        context[""enable_thinking""] = False"
      & LF & "    try:"
      & LF & "        return compiled.render(**context)"
      & LF & "    except Exception as e:"
      & LF & "        return ""REFUSED "" + type(e).__name__ + "": "" + str(e"
      & ")"
      & LF & ""
      & LF & "def compare(label, ours, theirs):"
      & LF & "    # A conversation both refuse -- a template that raises on a"
      & " shape it"
      & LF & "    # was not written for -- is agreed on; what is compared is "
      & "the text"
      & LF & "    # rendered, and neither rendered any."
      & LF & "    both_refused = ours.startswith(""REFUSED"") and theirs.star"
      & "tswith(""REFUSED"")"
      & LF & "    same = ours == theirs or both_refused"
      & LF & "    print(""%-32s %s"" % (label, ""same"" if same else ""DIFFER"
      & """) + ("" (both refused)"" if both_refused else """"))"
      & LF & "    if not same:"
      & LF & "        for line in difflib.unified_diff(theirs.split(""\n""), "
      & "ours.split(""\n""), ""jinja2"", ""this engine"", lineterm="""","
      & " n=1):"
      & LF & "            print(""    "" + line)"
      & LF & "    return same"
      & LF & ""
      & LF & "agreed = 0"
      & LF & "differed = 0"
      & LF & "if expressions:"
      & LF & "    for index, suite in enumerate(expression_suites):"
      & LF & "        with tempfile.NamedTemporaryFile(""w"", suffix="".jinja"
      & """, delete=False) as f:"
      & LF & "            f.write(suite)"
      & LF & "            name = f.name"
      & LF & "        ours = render_ours(expression_messages, False, False, ["
      & """--template"", name])"
      & LF & "        theirs = render_theirs(env.from_string(suite), expressi"
      & "on_messages, False, False)"
      & LF & "        os.unlink(name)"
      & LF & "        if compare(""expression suite %d"" % (index + 1), ours,"
      & " theirs):"
      & LF & "            agreed += 1"
      & LF & "        else:"
      & LF & "            differed += 1"
      & LF & "else:"
      & LF & "    source_args = [""--format"", fmt] if fmt else [""--template"
      & """, template]"
      & LF & "    for label, messages, add_generation, use_tools in conversat"
      & "ions:"
      & LF & "        if use_tools and without_tools:"
      & LF & "            continue"
      & LF & "        if label.startswith(""reasoning"") and without_reasonin"
      & "g:"
      & LF & "            continue"
      & LF & "        ours = render_ours(messages, add_generation, use_tools,"
      & " source_args)"
      & LF & "        theirs = render_theirs(tmpl, messages, add_generation, "
      & "use_tools)"
      & LF & "        if compare(label, ours, theirs):"
      & LF & "            agreed += 1"
      & LF & "        else:"
      & LF & "            differed += 1"
      & LF & "print(""cross: %d agree, %d differ"" % (agreed, differed))"
      & LF & "sys.exit(0 if differed == 0 else 1)";

   ---------
   -- Run --
   ---------

   function Run return Integer is
      Python : constant String :=
        Project_Tools.Processes.Locate_Command ("python3");
      Where  : constant String :=
        Ada.Directories.Compose (Ada.Directories.Current_Directory, "obj");
      Script : constant String :=
        Ada.Directories.Compose (Where, "jinja_cross.py");
      Binary : constant String := Ada.Command_Line.Command_Name;
      File   : Ada.Text_IO.File_Type;
   begin
      if Python = "" then
         Ada.Text_IO.Put_Line ("cross: skipped, no python3 on this machine");
         return 0;
      end if;

      if not Ada.Directories.Exists (Where) then
         Ada.Directories.Create_Path (Where);
      end if;
      Ada.Text_IO.Create (File, Ada.Text_IO.Out_File, Script);
      Ada.Text_IO.Put (File, Harness);
      Ada.Text_IO.New_Line (File);
      Ada.Text_IO.Close (File);

      --  The command line's own arguments, handed on whole, plus where
      --  this binary is so the program can call render.
      declare
         Count : constant Natural := Ada.Command_Line.Argument_Count;
         Args  : GNAT.OS_Lib.Argument_List (1 .. Count + 2);
         Status : Integer;
      begin
         Args (1) := new String'(Script);
         Args (2) := new String'("--binary");
         Args (3) := new String'(Binary);
         for Index in 2 .. Count loop
            Args (Index + 2) := new String'(Ada.Command_Line.Argument (Index));
         end loop;
         Status := Project_Tools.Processes.Run_Status
           (Label => "cross", Dir => Ada.Directories.Current_Directory,
            Program => Python, Args => Args);
         for Index in Args'Range loop
            GNAT.OS_Lib.Free (Args (Index));
         end loop;
         return Status;
      end;
   end Run;

end Crossing;
