with Ada.Command_Line;
with Ada.Directories;
with Ada.Text_IO;
with GNAT.OS_Lib;
with Project_Tools.Processes;

package body Crossing is

   LF : constant Character := Character'Val (10);

   --  The Python program, line by line. It is what it is because jinja2 is
   --  what it is; nothing in it decides anything about this engine.
   Harness : constant String :=
        "import sys, os, json, subprocess, difflib, datetime, tempfile"
      & LF & "try:"
      & LF & "    import jinja2"
      & LF & "except ImportError:"
      & LF & "    print(""cross: skipped, python3 has no jinja2"")"
      & LF & "    sys.exit(0)"
      & LF & ""
      & LF & "def option(name, default=None):"
      & LF & "    a = sys.argv"
      & LF & "    return a[a.index(name) + 1] if name in a and a.index(name) "
      & "+ 1 < len(a) else default"
      & LF & "binary = option(""--binary"")"
      & LF & "model = option(""--model"")"
      & LF & "template = option(""--template"")"
      & LF & "fmt = option(""--format"")"
      & LF & "think = ""think"" if ""--think"" in sys.argv else (""no-think"""
      & " if ""--no-think"" in sys.argv else None)"
      & LF & "expressions = ""--expressions"" in sys.argv"
      & LF & "without_tools = ""--without-tools"" in sys.argv"
      & LF & "without_reasoning = ""--without-reasoning"" in sys.argv"
      & LF & "record = option(""--record"")"
      & LF & "bos_given = option(""--bos"")"
      & LF & "eos_given = option(""--eos"")"
      & LF & "if not model or not binary:"
      & LF & "    print(""cross: --model PATH is required"")"
      & LF & "    sys.exit(1)"
      & LF & ""
      & LF & "def own_tokens():"
      & LF & "    r = subprocess.run([binary, ""render"", ""--model"", model,"
      & " ""--show-tokens""], capture_output=True, text=True)"
      & LF & "    lines = r.stdout.split(""\n"") if r.returncode == 0 else ["
      & """"", """"]"
      & LF & "    return lines[0], lines[1]"
      & LF & ""
      & LF & "def own_template():"
      & LF & "    # The model's own template, or the carried format named wit"
      & "h --format."
      & LF & "    r = subprocess.run([binary, ""render"", ""--model"", model,"
      & " ""--show-template""] + ([""--format"", fmt] if fmt else []), captur"
      & "e_output=True, text=True)"
      & LF & "    if r.returncode != 0:"
      & LF & "        print(""cross: the model's template would not read: "" "
      & "+ r.stderr.strip())"
      & LF & "        sys.exit(1)"
      & LF & "    return r.stdout"
      & LF & ""
      & LF & "if template:"
      & LF & "    source = open(template).read()"
      & LF & "    if source.endswith(""\n""):"
      & LF & "        source = source[:-1]"
      & LF & "else:"
      & LF & "    source = own_template()"
      & LF & "    if not template and not fmt:"
      & LF & "        template_file = tempfile.NamedTemporaryFile(""w"", suff"
      & "ix="".jinja"", delete=False)"
      & LF & "        template_file.write(source)"
      & LF & "        template_file.close()"
      & LF & "        template = template_file.name"
      & LF & ""
      & LF & "env = jinja2.Environment(trim_blocks=True, lstrip_blocks=True, "
      & "extensions=[""jinja2.ext.loopcontrols"", ""jinja2.ext.do""])"
      & LF & "def tojson(value, **keywords):"
      & LF & "    keywords.pop(""ensure_ascii"", None)"
      & LF & "    return json.dumps(value, ensure_ascii=False, **keywords)"
      & LF & "env.filters[""tojson""] = tojson"
      & LF & "env.globals[""strftime_now""] = lambda f: datetime.datetime.now"
      & "().strftime(f)"
      & LF & "def refuse(message):"
      & LF & "    raise Exception(message)"
      & LF & "env.globals[""raise_exception""] = refuse"
      & LF & ""
      & LF & "# The three filters the carried qwen3-coder and minicpm formats"
      & " stand on,"
      & LF & "# said in Python from the models' own templates: qwen_tool is t"
      & "he walk"
      & LF & "# Qwen3-Coder's template makes over one tool, run here through "
      & "jinja2 on"
      & LF & "# that template's own macro and loop body; qwen_params and para"
      & "ms write a"
      & LF & "# call's arguments as each template's mapping loop writes them."
      & LF & "QWEN_TOOL = """"""{% macro render_item_list(item_list, tag_name"
      & "='required') %}"
      & LF & "    {%- if item_list is defined and item_list is iterable and i"
      & "tem_list | length > 0 %}"
      & LF & "        {%- if tag_name %}{{- '\\n<' ~ tag_name ~ '>' -}}{% end"
      & "if %}"
      & LF & "            {{- '[' }}"
      & LF & "                {%- for item in item_list -%}"
      & LF & "                    {%- if loop.index > 1 %}{{- "", ""}}{% endi"
      & "f -%}"
      & LF & "                    {%- if item is string -%}"
      & LF & "                        {{ ""`"" ~ item ~ ""`"" }}"
      & LF & "                    {%- else -%}"
      & LF & "                        {{ item }}"
      & LF & "                    {%- endif -%}"
      & LF & "                {%- endfor -%}"
      & LF & "            {{- ']' }}"
      & LF & "        {%- if tag_name %}{{- '</' ~ tag_name ~ '>' -}}{% endif"
      & " %}"
      & LF & "    {%- endif %}"
      & LF & "{% endmacro %}"
      & LF & "{%- if tool.function is defined %}"
      & LF & "    {%- set tool = tool.function %}"
      & LF & "{%- endif %}"
      & LF & "{{- ""\\n<function>\\n<name>"" ~ tool.name ~ ""</name>"" }}"
      & LF & "{{- '\\n<description>' ~ (tool.description | trim) ~ '</descrip"
      & "tion>' }}"
      & LF & "{{- '\\n<parameters>' }}"
      & LF & "{%- for param_name, param_fields in tool.parameters.properties|"
      & "items %}"
      & LF & "    {{- '\\n<parameter>' }}"
      & LF & "    {{- '\\n<name>' ~ param_name ~ '</name>' }}"
      & LF & "    {%- if param_fields.type is defined %}"
      & LF & "        {{- '\\n<type>' ~ (param_fields.type | string) ~ '</typ"
      & "e>' }}"
      & LF & "    {%- endif %}"
      & LF & "    {%- if param_fields.description is defined %}"
      & LF & "        {{- '\\n<description>' ~ (param_fields.description | tr"
      & "im) ~ '</description>' }}"
      & LF & "    {%- endif %}"
      & LF & "    {{- render_item_list(param_fields.enum, 'enum') }}"
      & LF & "    {%- set handled_keys = ['type', 'description', 'enum', 'req"
      & "uired'] %}"
      & LF & "    {%- for json_key, json_value in param_fields|items %}"
      & LF & "        {%- if json_key not in handled_keys %}"
      & LF & "            {%- set normed_json_key = json_key|string %}"
      & LF & "            {%- if json_value is mapping %}"
      & LF & "                {{- '\\n<' ~ normed_json_key ~ '>' ~ (json_valu"
      & "e | tojson | safe) ~ '</' ~ normed_json_key ~ '>' }}"
      & LF & "            {%- else %}"
      & LF & "                {{- '\\n<' ~ normed_json_key ~ '>' ~ (json_valu"
      & "e | string) ~ '</' ~ normed_json_key ~ '>' }}"
      & LF & "            {%- endif %}"
      & LF & "        {%- endif %}"
      & LF & "    {%- endfor %}"
      & LF & "    {{- render_item_list(param_fields.required, 'required') }}"
      & LF & "    {{- '\\n</parameter>' }}"
      & LF & "{%- endfor %}"
      & LF & "{{- render_item_list(tool.parameters.required, 'required') }}"
      & LF & "{{- '\\n</parameters>' }}"
      & LF & "{%- if tool.return is defined %}"
      & LF & "    {%- if tool.return is mapping %}"
      & LF & "        {{- '\\n<return>' ~ (tool.return | tojson | safe) ~ '</"
      & "return>' }}"
      & LF & "    {%- else %}"
      & LF & "        {{- '\\n<return>' ~ (tool.return | string) ~ '</return>"
      & "' }}"
      & LF & "    {%- endif %}"
      & LF & "{%- endif %}"
      & LF & "{{- '\\n</function>' }}"""""""
      & LF & "qwen_tool_template = env.from_string(QWEN_TOOL)"
      & LF & "env.filters[""qwen_tool""] = lambda tool: qwen_tool_template.re"
      & "nder(tool=tool)"
      & LF & "def spoken(value):"
      & LF & "    return value if isinstance(value, str) else str(value)"
      & LF & "env.filters[""qwen_params""] = lambda args: """".join(""<parame"
      & "ter=%s>\n%s\n</parameter>\n"" % (k, spoken(v)) for k, v in args.item"
      & "s())"
      & LF & "def param(k, v):"
      & LF & "    if isinstance(v, str) and any(c in v for c in ""<&\n""):"
      & LF & "        return '<param name=""%s""><![CDATA[%s]]></param>' % (k"
      & ", v)"
      & LF & "    return '<param name=""%s"">%s</param>' % (k, spoken(v))"
      & LF & "env.filters[""params""] = lambda args: """".join(param(k, v) fo"
      & "r k, v in args.items())"
      & LF & "tmpl = env.from_string(source)"
      & LF & "bos_token, eos_token = own_tokens()"
      & LF & "if bos_given is not None:"
      & LF & "    bos_token = bos_given"
      & LF & "if eos_given is not None:"
      & LF & "    eos_token = eos_given"
      & LF & ""
      & LF & "tools = ["
      & LF & " {""type"": ""function"", ""function"": {""name"": ""calc"", """
      & "description"": "" Evaluate a binary arithmetic operation. "","
      & LF & "  ""parameters"": {""type"": ""object"", ""properties"": {"
      & LF & "    ""a"": {""type"": ""integer"", ""description"": ""left oper"
      & "and""},"
      & LF & "    ""op"": {""type"": ""string"", ""enum"": [""+"", ""-"", ""*"
      & """, ""/""], ""description"": ""the operator""},"
      & LF & "    ""b"": {""type"": ""integer""},"
      & LF & "    ""exact"": {""type"": ""boolean"", ""default"": False, ""mi"
      & "nimum"": 0},"
      & LF & "    ""tags"": {""type"": ""array"", ""items"": {""type"": ""str"
      & "ing""}}},"
      & LF & "   ""required"": [""a"", ""op"", ""b""]}, ""return"": {""type"""
      & ": ""number""}}},"
      & LF & " {""type"": ""function"", ""function"": {""name"": ""weather"","
      & " ""description"": ""Look up the weather."","
      & LF & "  ""parameters"": {""type"": ""object"", ""properties"": {"
      & LF & "    ""city"": {""type"": ""string"", ""description"": ""which c"
      & "ity"", ""enum"": [""Aarhus"", ""Odense""], ""required"": [""city""]}"
      & "}}}}]"
      & LF & ""
      & LF & "def call(name, arguments):"
      & LF & "    return {""function"": {""name"": name, ""arguments"": argum"
      & "ents}}"
      & LF & "conversations = ["
      & LF & " (""plain"", [{""role"": ""user"", ""content"": ""hi""}], True,"
      & " False),"
      & LF & " (""system and user"", [{""role"": ""system"", ""content"": ""B"
      & "e brief.""}, {""role"": ""user"", ""content"": ""hi""}], True, False"
      & "),"
      & LF & " (""tools, no system"", [{""role"": ""user"", ""content"": ""ad"
      & "d 2 and 3""}], True, True),"
      & LF & " (""tools with system"", [{""role"": ""system"", ""content"": "
      & """Be brief.""}, {""role"": ""user"", ""content"": ""add""}], True, T"
      & "rue),"
      & LF & " (""call turn with text"", [{""role"": ""user"", ""content"": "
      & """add""},"
      & LF & "   {""role"": ""assistant"", ""content"": ""  Let me compute.  "
      & """, ""tool_calls"": [call(""calc"", {""a"": 2, ""op"": ""+"", ""b"":"
      & " 3})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""5""}, {""role"": ""tool"
      & """, ""content"": ""5 again""}, {""role"": ""user"", ""content"": ""t"
      & "hanks""}], True, True),"
      & LF & " (""call turn without text"", [{""role"": ""user"", ""content"""
      & ": ""add""},"
      & LF & "   {""role"": ""assistant"", ""content"": """", ""tool_calls"":"
      & " [call(""calc"", {""a"": 2, ""op"": ""*"", ""b"": 3, ""exact"": True"
      & "})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""6""}], True, True),"
      & LF & " (""two calls"", [{""role"": ""user"", ""content"": ""add""},"
      & LF & "   {""role"": ""assistant"", ""content"": """", ""tool_calls"":"
      & " [call(""calc"", {""a"": 1, ""op"": ""+"", ""b"": 1}), call(""weathe"
      & "r"", {""city"": ""Odense""})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""2""}, {""role"": ""tool"
      & """, ""content"": ""rain""}, {""role"": ""assistant"", ""content"": "
      & """done""}], False, True),"
      & LF & " (""reply, no generation prompt"", [{""role"": ""user"", ""cont"
      & "ent"": ""hi""}, {""role"": ""assistant"", ""content"": ""yo""}], Fal"
      & "se, False),"
      & LF & " (""reasoning kept and dropped"", [{""role"": ""user"", ""conte"
      & "nt"": ""q1""}, {""role"": ""assistant"", ""content"": ""<think>\nfir"
      & "st\n</think>\n\nA1""},"
      & LF & "   {""role"": ""user"", ""content"": ""q2""}, {""role"": ""assi"
      & "stant"", ""content"": ""<think>\nsecond\n</think>\n\nA2""}], True, F"
      & "alse),"
      & LF & " (""nested arguments"", [{""role"": ""user"", ""content"": ""go"
      & """},"
      & LF & "   {""role"": ""assistant"", ""content"": """", ""tool_calls"":"
      & " [call(""calc"", {""a"": {""x"": 1, ""y"": [True, None]}, ""l"": [1,"
      & " ""two""], ""s"": ""str"", ""n"": 2.5})]},"
      & LF & "   {""role"": ""tool"", ""content"": ""{\""ok\"": true}""}], Tr"
      & "ue, True),"
      & LF & " (""tool-wrapped user turn"", [{""role"": ""user"", ""content"""
      & ": ""<tool_response>\nfrom before\n</tool_response>""}, {""role"": """
      & "assistant"", ""content"": ""noted""},"
      & LF & "   {""role"": ""user"", ""content"": ""<tool_response>x</tool_r"
      & "esponse>""}], True, False),"
      & LF & " (""two system turns"", [{""role"": ""system"", ""content"": """
      & "First.""}, {""role"": ""system"", ""content"": ""Second.""}, {""role"
      & """: ""user"", ""content"": ""hi""}], True, False),"
      & LF & " (""developer turn"", [{""role"": ""developer"", ""content"": "
      & """Answer tersely.""}, {""role"": ""user"", ""content"": ""hi""}], Tr"
      & "ue, False),"
      & LF & " (""content in parts"", [{""role"": ""user"", ""content"": [{"""
      & "type"": ""image""}, {""type"": ""text"", ""text"": "" what is this "
      & """}, {""type"": ""video""}]}], True, False),"
      & LF & " (""reply in parts"", [{""role"": ""user"", ""content"": ""hi"""
      & "}, {""role"": ""assistant"", ""content"": [{""type"": ""text"", ""te"
      & "xt"": "" a cat ""}, {""type"": ""image""}]}, {""role"": ""user"", """
      & "content"": ""sure?""}], True, False),"
      & LF & " (""tool answer in parts"", [{""role"": ""user"", ""content"": "
      & """weather?""}, {""role"": ""assistant"", ""content"": """", ""tool_c"
      & "alls"": [{""type"": ""function"", ""function"": {""name"": ""weather"
      & """, ""arguments"": {""city"": ""Aarhus""}}}]}, {""role"": ""tool"", "
      & """content"": [{""type"": ""text"", ""text"": ""12 C""}, {""type"": "
      & """image""}]}], True, True),"
      & LF & "]"
      & LF & "expression_messages = [{""role"": ""system"", ""content"": ""s"
      & """}, {""role"": ""user"", ""content"": ""hi""}, {""role"": ""assista"
      & "nt"", ""content"": ""yo""}, {""role"": ""user"", ""content"": ""agai"
      & "n""}]"
      & LF & "expression_suites = ["
      & LF & " ""{% set l = ['b', 'a', 'c', 'a'] %}{{ l | join(', ') }}|{{ l "
      & "| sort | join }}|{{ l | sort(reverse=true) | join }}|{{ l | unique |"
      & " join }}|{{ [3, 1, 2] | sort | join('-') }}|{{ l | select('equalto',"
      & " 'a') | list | length }}|{{ l | reject('equalto', 'a') | join }}|{{ "
      & "'abc' | list | join('.') }}"","
      & LF & " ""{{ messages | map(attribute='role') | join(',') }}|{{ messag"
      & "es | selectattr('role', 'equalto', 'user') | map(attribute='content'"
      & ") | join('+') }}|{{ messages | rejectattr('role', 'equalto', 'user')"
      & " | list | length }}|{{ (messages | first).role }}|{{ (messages | las"
      & "t)['content'] }}"","
      & LF & " ""{{ 'a\\nb\\n\\nc' | indent(2) }}|{{ 'a\\nb' | indent(width=1"
      & ", first=True) }}|{{ 'a\\n\\nb' | indent(3, blank=True) }}"","
      & LF & " ""{% set d = {'a': 1, 'b': 'x', 'c': [1, 2], 'd': {'e': true}}"
      & " %}{{ d }}|{{ d | tojson }}|{{ d.a + 1 }}|{{ d.keys() | join(',') }}"
      & "|{{ d.values() | length }}|{{ d.get('b') }}{{ d.get('zz', 'none') }}"
      & "|{% for k, v in d | dictsort %}{{ k }}={{ v }};{% endfor %}|{{ d.d.e"
      & " }}|{{ {'x': messages[0].role} | tojson }}|{{ d | tojson(indent=2) }"
      & "}"","
      & LF & " ""{% set m = {'z': 1, 'a': 2} %}{% for k, v in m.items() %}{{ "
      & "k }}{% endfor %}{% for k, v in m | dictsort %}{{ k }}{% endfor %}{% "
      & "for k, v in m | dictsort(by='value', reverse=true) %}{{ k }}{% endfo"
      & "r %}{% if 'a' in m.keys() %}y{% endif %}{% for a, b in [[1, 2], [3, "
      & "4]] %}{{ a + b }}{% endfor %}"","
      & LF & " ""{% for i in range(5) %}{% if i == 1 %}{% continue %}{% endif"
      & " %}{% if i == 3 %}{% break %}{% endif %}{{ i }}{% endfor %}|{% for m"
      & " in messages %}{{ loop.length }}{{ loop.revindex }}{{ loop.revindex0"
      & " }}{% endfor %}|{% filter upper %}ab{{ 'c' }}{% endfilter %}|{% for "
      & "i in range(2, 9, 3) %}{{ loop.length }}{{ loop.revindex }}{% endfor "
      & "%}"","
      & LF & " ""{% macro box(title) %}<{{ title }}>{{ caller() }}</{{ title "
      & "}}>{% endmacro %}{% call box('b') %}inner {{ 1 + 1 }}{% endcall %}|{"
      & "% set t = 'x' %}{% call box(t) %}{% call box('n') %}deep{% endcall %"
      & "}{% endcall %}|{% macro two(t) %}[{{ caller(1, 'z') }}]{% endmacro %"
      & "}{% call(n, s) two('q') %}{{ n + 1 }}{{ s }}{% endcall %}"","
      & LF & " ""{% set i = 1 %}{{ i + 1 }}{% set j = i %}{{ j + i }}{% set t"
      & " = '1' %}{{ t + '1' }}{{ t ~ i }}{% if i == '1' %}!{% endif %}{% if "
      & "i == 1 %}y{% endif %}{% if t == '1' %}z{% endif %}{% if i is number "
      & "and t is not number %}n{% endif %}{% if i is string %}!{% endif %}{%"
      & " if (i | string) is string %}s{% endif %}{{ messages | length + 1 }}"
      & "{{ '7' | int + 1 }}{{ 'x' ~ 1 + 2 ~ 'y' }}"","
      & LF & " ""[{{ 1 == 1 }}][{{ nothing is defined }}][{{ true }}][{{ fals"
      & "e }}][{{ none }}][{{ 'ab'.startswith('a') }}]{% set ok = 1 == 2 %}{{"
      & " ok }}{{ ok | tojson }}{% if (1 == 1) != (2 == 3) %}y{% endif %}{% f"
      & "or m in messages %}{{ m.role + ('!' if loop.first else '') }}{% endf"
      & "or %}"","
      & LF & " ""{% set l = [['b', 'c'], 'd'] %}{{ l[0][1] }}{{ l[1][0] }}{{ "
      & "messages[0].role[0] }}{{ messages[0]['content'][0] }}{{ 'a|b'.split("
      & "'|')[1].upper() }}{{ (messages | selectattr('role', 'equalto', 'user"
      & "') | list)[0].content }}"","
      & LF & " ""{{ messages | selectattr('role', 'equalto', 'assistant') | m"
      & "ap(attribute='content') | list | tojson }}|{{ messages | map(attribu"
      & "te='role') | unique | list | length }}|{{ messages | rejectattr('rol"
      & "e', 'equalto', 'system') | map(attribute='role') | join('/') }}|{{ m"
      & "essages | selectattr('role', 'in', ['user', 'system']) | list | leng"
      & "th }}|{{ messages | select('mapping') | list | length }}|{{ messages"
      & " | map(attribute='content') | select('equalto', 'yo') | join }}"","
      & LF & " ""{{ 0.1 + 0.2 }}|{{ 7 / 2 }}|{{ 8 / 2 }}|{{ 1.5 + 1 }}|{{ 2.5"
      & " * 2 }}|{{ 7.5 // 2 }}|{{ 7.5 % 2 }}|{{ 1e16 * 1.0 }}|{{ 1.0e15 }}|{"
      & "{ 0.00001 * 1 }}|{{ 0.0001 * 1 }}|{{ 2.0 }}|{{ 1 / 3 }}|{{ -1.5 - 1 "
      & "}}|{{ [2.5, 1.5, 3] | min }}|{{ [2.5, 1.5, 3] | sort | join(',') }}|"
      & "{% if 1.5 > 1 and 0.5 < 1 %}c{% endif %}|{{ '3' | float }}{{ 1.25 | "
      & "tojson }}|{{ 123456789012345678.0 * 1 }}|{{ 100.0 * 100 }}|{{ 1.5 | "
      & "int }}|{{ {'x': 0.5} | tojson }}|{% for v in [0.5, 2] %}{{ v * 2 }}{"
      & "% endfor %}"","
      & LF & " ""{%- set content = [{'type': 'image'}, {'type': 'text', 'text"
      & "': ' hello '}] -%}{%- if content is string -%}{{ content | trim }}{%"
      & "- elif content is iterable -%}{%- for item in content -%}{%- if item"
      & "['type'] == 'image' -%}{{ '<start_of_image>' }}{%- elif item['type']"
      & " == 'text' -%}{{ item['text'] | trim }}{%- endif -%}{%- endfor -%}{%"
      & "- else -%}{{ raise_exception(\""Invalid content type\"") }}{%- endif"
      & " -%}|{%- set image_count = namespace(value=0) %}{%- macro render_con"
      & "tent(content, do_vision_count) %}{%- if content is string %}{{- cont"
      & "ent }}{%- elif content is iterable and content is not mapping %}{%- "
      & "for item in content %}{%- if 'image' in item or 'image_url' in item "
      & "or item.type == 'image' %}{%- if do_vision_count %}{%- set image_cou"
      & "nt.value = image_count.value + 1 %}{%- endif %}{{- 'Picture ' ~ imag"
      & "e_count.value ~ ': ' }}{{- '<|vision_start|><|image_pad|><|vision_en"
      & "d|>' }}{%- elif 'text' in item %}{{- item.text }}{%- else %}{{- rais"
      & "e_exception('Unexpected item type in content.') }}{%- endif %}{%- en"
      & "dfor %}{%- elif content is none or content is undefined %}{{- '' }}{"
      & "%- else %}{{- raise_exception('Unexpected content type.') }}{%- endi"
      & "f %}{%- endmacro %}{{ render_content([{'type': 'image'}, {'text': ' "
      & "t '}, {'image_url': 'u'}], true) }}|{{ image_count.value }}|{{ rende"
      & "r_content('plain', false) }}|{{ render_content(none, false) }}|"","
      & LF & " ""{{ 2.5 | round }}|{{ 3.5 | round }}|{{ 2.567 | round(2) }}|{"
      & "{ 2.5 | round(0, 'ceil') }}|{{ 2.5 | round(method='floor') }}|{{ 42 "
      & "| round }}|{{ -3 | abs }}{{ -2.5 | abs }}|{{ [1, 2, 3] | sum }}|{{ ["
      & "1.5, 2] | sum }}|{{ [1, 2] | sum(start=10) }}|{{ [{'n': 2}, {'n': 3}"
      & "] | sum(attribute='n') }}|{{ 'a b/c&d=\u00e9' | urlencode }}|{{ {'a "
      & "b': 'c&d', 'x': 1} | urlencode }}|{{ '  xx  ' | trim }}[{{ 'xxaxx' |"
      & " trim('x') }}]|{{ 'a-a-a' | replace('-', '+', 1) }}|{{ messages | co"
      & "unt }}|{{ 2 * 3 ** 2 }}{{ 2 ** -1 }}{% if 1.0 == 1 %}e{% endif %}"","
      & LF & " ""{{ [1, 2, 3, 4, 5] | batch(2) | list | tojson }}|{{ [1, 2, 3"
      & ", 4, 5] | batch(2, 0) | list | tojson }}|{{ [1, 2, 3, 4, 5] | slice("
      & "3) | list | tojson }}|{{ [1, 2, 3, 4, 5] | slice(3, 'x') | list | to"
      & "json }}|{% for row in [1, 2, 3] | batch(2) %}[{{ row | join(',') }}]"
      & "{% endfor %}|{% for g, items in messages | groupby('role') %}{{ g }}"
      & ":{{ items | length }};{% endfor %}|{% for group in messages | groupb"
      & "y('role') %}{{ group.grouper }}={{ group.list | map(attribute='conte"
      & "nt') | join('+') }};{% endfor %}|{{ (messages | first) | attr('role'"
      & ") }}"","
      & LF & " ""{{ 'ab' | center(5) }}|{{ 'ab' | center(6) }}|{{ 'abc' | cen"
      & "ter(2) }}|{{ 'Hello world this is a test of wrapping words' | wordwr"
      & "ap(10) }}|{{ 'averyveryverylongword short' | wordwrap(8) }}|{{ 'a\nb"
      & " c d e f g' | wordwrap(5) }}|{{ 'hello world foo' | truncate(9) }}|{"
      & "{ 'hello world foo' | truncate(9, True) }}|{{ 'hello world' | trunca"
      & "te(12) }}|{{ 'hello world foo' | truncate(9, False, '..', 0) }}|{{ '"
      & "%s is %d and %.2f %%' | format('x', 3, 1.5) }}|{{ '<b>hi</b> <i>ther"
      & "e</i>  x' | striptags }}|{{ [1, 2] | pprint }}|{{ {'a': 1} | pprint "
      & "}}|{{ 'x' | pprint }}|{{ 'abc' | reverse }}|{{ [1, 2, 3] | reverse |"
      & " list }}|{{ [1, 5, 3] | max }}|{{ [{'n': 2}, {'n': 5}] | max(attribu"
      & "te='n') }}|{{ 'ab' | wordwrap(1) }}|{{ 'hello world this is long' | "
      & "wordwrap(10, break_long_words=False, wrapstring='|') }}"","
      & LF & " ""{% with a = 1, b = 'x' %}{{ a }}{{ b }}{% set a = 2 %}{{ a }"
      & "}{% endwith %}[{% if a is defined %}!{% endif %}]{% set a = 9 %}{% w"
      & "ith a = 1 %}{{ a }}{% endwith %}{{ a }}|{% raw %}{{ not rendered }} "
      & "{% if %}{% endraw %}|{% set l = [] %}{% do l.append(1) %}{% do l.app"
      & "end('x') %}{% do l.extend([2, 3]) %}{{ l }}{% set d = {'a': 1} %}{% "
      & "do d.update({'b': 2}) %}{{ d }}{% do 1 + 1 %}|{% set ns = namespace("
      & "items=[]) %}{% for m in messages %}{% do ns.items.append(m.role) %}{"
      & "% endfor %}{{ ns.items | join(',') }}"","
      & LF & " ""{{ [1, 2, 3] | select('number') | join(',') }}|{{ ['a', none"
      & ", 'b'] | select('defined') | list | length }}|{{ ['a', none, 'b'] | "
      & "reject('none') | join }}|{{ [3, 1, 2] | sort(reverse=True) | first }"
      & "}|{{ ['B', 'a', 'C'] | sort | join }}|{{ ['B', 'a', 'C'] | sort(case"
      & "_sensitive=True) | join }}|{% for m in messages[1:] %}{{ m.role[0] }"
      & "}{% endfor %}{% for m in messages[:2] %}{{ m.role[0] }}{% endfor %}|"
      & "{{ (messages[0].nothing or 'd') }}{{ (messages[0].role and 'a') }}|{"
      & "% if 'role' in messages[0] and 'x' not in {'a': 1} %}m{% endif %}"","
      & LF & "]"
      & LF & ""
      & LF & "def render_ours(messages, add_generation, use_tools, source_arg"
      & "s):"
      & LF & "    args = [binary, ""render"", ""--model"", model] + source_ar"
      & "gs"
      & LF & "    for m in messages:"
      & LF & "        if m[""role""] == ""system"":"
      & LF & "            args += [""--system"", m[""content""]]"
      & LF & "        elif m[""role""] == ""developer"":"
      & LF & "            args += [""--developer"", m[""content""]]"
      & LF & "        elif m[""role""] == ""user"" and isinstance(m[""content"
      & """], list):"
      & LF & "            args += [""--prompt-parts"", json.dumps(m[""content"
      & """], ensure_ascii=False)]"
      & LF & "        elif m[""role""] == ""user"":"
      & LF & "            args += [""--prompt"", m[""content""]]"
      & LF & "        elif m[""role""] == ""assistant"" and isinstance(m.get("
      & """content""), list):"
      & LF & "            args += [""--assistant-parts"", json.dumps(m[""cont"
      & "ent""], ensure_ascii=False)]"
      & LF & "        elif m[""role""] == ""assistant"":"
      & LF & "            args += [""--assistant"", m.get(""content"", """")]"
      & LF & "            for c in m.get(""tool_calls"", []):"
      & LF & "                args += [""--calls"", json.dumps({""name"": c["
      & """function""][""name""], ""arguments"": c[""function""][""arguments"
      & """]}, ensure_ascii=False)]"
      & LF & "        elif m[""role""] == ""tool"" and isinstance(m[""content"
      & """], list):"
      & LF & "            args += [""--tool-parts"", json.dumps(m[""content"""
      & "], ensure_ascii=False)]"
      & LF & "        elif m[""role""] == ""tool"":"
      & LF & "            args += [""--tool"", m[""content""]]"
      & LF & "    if use_tools:"
      & LF & "        args += [""--tools"", json.dumps(tools, ensure_ascii=Fa"
      & "lse)]"
      & LF & "    if add_generation:"
      & LF & "        args += [""--generation-prompt""]"
      & LF & "    if think == ""think"":"
      & LF & "        args += [""--think""]"
      & LF & "    if think == ""no-think"":"
      & LF & "        args += [""--no-think""]"
      & LF & "    r = subprocess.run(args, capture_output=True, text=True)"
      & LF & "    return r.stdout if r.returncode == 0 else ""REFUSED "" + r."
      & "stderr.strip()"
      & LF & ""
      & LF & "def render_theirs(compiled, messages, add_generation, use_tools"
      & "):"
      & LF & "    context = dict(messages=messages, add_generation_prompt=add"
      & "_generation, bos_token=bos_token, eos_token=eos_token)"
      & LF & "    if use_tools:"
      & LF & "        context[""tools""] = tools"
      & LF & "    if think == ""think"":"
      & LF & "        context[""enable_thinking""] = True"
      & LF & "    if think == ""no-think"":"
      & LF & "        context[""enable_thinking""] = False"
      & LF & "    try:"
      & LF & "        return compiled.render(**context)"
      & LF & "    except Exception as e:"
      & LF & "        return ""REFUSED "" + type(e).__name__ + "": "" + str(e"
      & ")"
      & LF & ""
      & LF & "def compare(label, ours, theirs):"
      & LF & "    # A conversation both refuse -- a template that raises on a"
      & " shape it"
      & LF & "    # was not written for -- is agreed on; what is compared is "
      & "the text"
      & LF & "    # rendered, and neither rendered any."
      & LF & "    both_refused = ours.startswith(""REFUSED"") and theirs.star"
      & "tswith(""REFUSED"")"
      & LF & "    same = ours == theirs or both_refused"
      & LF & "    print(""%-32s %s"" % (label, ""same"" if same else ""DIFFER"
      & """) + ("" (both refused)"" if both_refused else """"))"
      & LF & "    if not same:"
      & LF & "        for line in difflib.unified_diff(theirs.split(""\n""), "
      & "ours.split(""\n""), ""jinja2"", ""this engine"", lineterm="""", n=1)"
      & ":"
      & LF & "            print(""    "" + line)"
      & LF & "    return same"
      & LF & ""
      & LF & "agreed = 0"
      & LF & "differed = 0"
      & LF & "recorded = []"
      & LF & "if expressions:"
      & LF & "    for index, suite in enumerate(expression_suites):"
      & LF & "        with tempfile.NamedTemporaryFile(""w"", suffix="".jinja"
      & """, delete=False) as f:"
      & LF & "            f.write(suite)"
      & LF & "            name = f.name"
      & LF & "        ours = render_ours(expression_messages, False, False, ["
      & """--template"", name])"
      & LF & "        theirs = render_theirs(env.from_string(suite), expressi"
      & "on_messages, False, False)"
      & LF & "        os.unlink(name)"
      & LF & "        if compare(""expression suite %d"" % (index + 1), ours,"
      & " theirs):"
      & LF & "            agreed += 1"
      & LF & "        else:"
      & LF & "            differed += 1"
      & LF & "else:"
      & LF & "    source_args = [""--format"", fmt] if fmt else [""--template"
      & """, template]"
      & LF & "    for label, messages, add_generation, use_tools in conversat"
      & "ions:"
      & LF & "        if use_tools and without_tools:"
      & LF & "            continue"
      & LF & "        if label.startswith(""reasoning"") and without_reasonin"
      & "g:"
      & LF & "            continue"
      & LF & "        ours = render_ours(messages, add_generation, use_tools,"
      & " source_args)"
      & LF & "        theirs = render_theirs(tmpl, messages, add_generation, "
      & "use_tools)"
      & LF & "        if compare(label, ours, theirs):"
      & LF & "            agreed += 1"
      & LF & "        else:"
      & LF & "            differed += 1"
      & LF & "        recorded.append((conversations.index((label, messages, "
      & "add_generation, use_tools)) + 1, theirs))"
      & LF & "print(""cross: %d agree, %d differ"" % (agreed, differed))"
      & LF & "if record:"
      & LF & "    # What jinja2 rendered, for the suite to compare bytes agai"
      & "nst without"
      & LF & "    # Python: one case a record, the conversation's number, the"
      & " thinking"
      & LF & "    # choice, the byte count -- minus one for a refusal -- and "
      & "the bytes."
      & LF & "    dated = not os.path.exists(record)"
      & LF & "    with open(record, ""a"", encoding=""utf-8"") as f:"
      & LF & "        if dated:"
      & LF & "            # The day it was recorded, so that a template writi"
      & "ng the date"
      & LF & "            # can be compared on another day."
      & LF & "            f.write(""date %s\n"" % datetime.date.today().isofo"
      & "rmat())"
      & LF & "        for number, text in recorded:"
      & LF & "            refused = text.startswith(""REFUSED"")"
      & LF & "            body = """" if refused else text"
      & LF & "            f.write(""case %d %s %d\n"" % (number, think or ""u"
      & "nstated"", -1 if refused else len(body.encode(""utf-8""))))"
      & LF & "            f.write(body + ""\n"")"
      & LF & "sys.exit(0 if differed == 0 else 1)";

   ---------
   -- Run --
   ---------

   function Run return Integer is
      Python : constant String :=
        Project_Tools.Processes.Locate_Command ("python3");
      Where  : constant String :=
        Ada.Directories.Compose (Ada.Directories.Current_Directory, "obj");
      Script : constant String :=
        Ada.Directories.Compose (Where, "jinja_cross.py");
      Binary : constant String := Ada.Command_Line.Command_Name;
      File   : Ada.Text_IO.File_Type;
   begin
      if Python = "" then
         Ada.Text_IO.Put_Line ("cross: skipped, no python3 on this machine");
         return 0;
      end if;

      if not Ada.Directories.Exists (Where) then
         Ada.Directories.Create_Path (Where);
      end if;
      Ada.Text_IO.Create (File, Ada.Text_IO.Out_File, Script);
      Ada.Text_IO.Put (File, Harness);
      Ada.Text_IO.New_Line (File);
      Ada.Text_IO.Close (File);

      --  The command line's own arguments, handed on whole, plus where
      --  this binary is so the program can call render.
      declare
         Count : constant Natural := Ada.Command_Line.Argument_Count;
         Args  : GNAT.OS_Lib.Argument_List (1 .. Count + 2);
         Status : Integer;
      begin
         Args (1) := new String'(Script);
         Args (2) := new String'("--binary");
         Args (3) := new String'(Binary);
         for Index in 2 .. Count loop
            Args (Index + 2) := new String'(Ada.Command_Line.Argument (Index));
         end loop;
         Status := Project_Tools.Processes.Run_Status
           (Label => "cross", Dir => Ada.Directories.Current_Directory,
            Program => Python, Args => Args);
         for Index in Args'Range loop
            GNAT.OS_Lib.Free (Args (Index));
         end loop;
         return Status;
      end;
   end Run;

end Crossing;
