with Ada.Directories;
with Ada.Streams.Stream_IO;
with Ada.Text_IO;

package body Shader_Generation is

   use type Interfaces.Unsigned_32;
   use type Interfaces.Unsigned_64;

   --  A number in hexadecimal, without the base Ada would write.
   function Hex (Value : Interfaces.Unsigned_64) return String is
      Digits_Of : constant String := "0123456789ABCDEF";
      Room      : String (1 .. 16) := [others => '0'];
      Left      : Interfaces.Unsigned_64 := Value;
   begin
      for Index in reverse Room'Range loop
         Room (Index) := Digits_Of (Natural (Left and 16#F#) + 1);
         Left := Interfaces.Shift_Right (Left, 4);
      end loop;
      return Room;
   end Hex;

   function Hex (Value : Interfaces.Unsigned_32) return String is
      Digits_Of : constant String := "0123456789ABCDEF";
      Room      : String (1 .. 8) := [others => '0'];
      Left      : Interfaces.Unsigned_32 := Value;
   begin
      for Index in reverse Room'Range loop
         Room (Index) := Digits_Of (Natural (Left and 16#F#) + 1);
         Left := Interfaces.Shift_Right (Left, 4);
      end loop;
      return Room;
   end Hex;

   --  Read a whole file as bytes, or report that it could not be.
   procedure Read_All
     (Path  : String;
      Room  : out Ada.Streams.Stream_Element_Array;
      Last  : out Ada.Streams.Stream_Element_Offset;
      Found : out Boolean)
   is
      use Ada.Streams;
      Handle : Stream_IO.File_Type;
   begin
      Last := 0;
      Found := False;

      if not Ada.Directories.Exists (Path) then
         return;
      end if;

      Stream_IO.Open (Handle, Stream_IO.In_File, Path);
      Stream_IO.Read (Handle, Room, Last);
      Stream_IO.Close (Handle);
      Found := True;
   exception
      when others =>
         Found := False;
   end Read_All;

   --------------------
   -- Source_Digest --
   --------------------

   function Source_Digest
     (Path : String; Found : out Boolean) return Interfaces.Unsigned_64
   is
      use Ada.Streams;

      Room   : Stream_Element_Array (1 .. 1_000_000);
      Last   : Stream_Element_Offset;
      Digest : Interfaces.Unsigned_64 := 16#CBF2_9CE4_8422_2325#;
   begin
      Read_All (Path, Room, Last, Found);
      if not Found then
         return 0;
      end if;

      --  Every byte but the ones a line ending differs by, so that a file
      --  checked out on another host has the same digest as here.
      for Index in 1 .. Last loop
         if Room (Index) /= 13 then
            Digest :=
              (Digest xor Interfaces.Unsigned_64 (Room (Index)))
              * 16#0000_0100_0000_01B3#;
         end if;
      end loop;

      return Digest;
   end Source_Digest;

   -------------------
   -- Write_Shader --
   -------------------

   procedure Write_Shader
     (Root     : String;
      Source   : String;
      Compiled : String;
      Written  : out Boolean)
   is
      use Ada.Streams;

      Room : Stream_Element_Array (1 .. 1_000_000);
      Last : Stream_Element_Offset;
      Read : Boolean;

      Digest : Interfaces.Unsigned_64;
      Marked : Boolean;

      Target : constant String :=
        Root & "/src/library/model_runner-shaders.ads";

      Handle : Ada.Text_IO.File_Type;
   begin
      Written := False;

      Read_All (Compiled, Room, Last, Read);
      if not Read or else Last = 0 or else Last mod 4 /= 0 then
         return;
      end if;

      Digest := Source_Digest (Source, Marked);
      if not Marked then
         return;
      end if;

      Ada.Text_IO.Create (Handle, Ada.Text_IO.Out_File, Target);

      Ada.Text_IO.Put_Line (Handle, "with Interfaces;");
      Ada.Text_IO.New_Line (Handle);
      Ada.Text_IO.Put_Line
        (Handle, "--  Compiled shaders, as the words a device is given.");
      Ada.Text_IO.Put_Line (Handle, "--");
      Ada.Text_IO.Put_Line
        (Handle,
         "--  Generated by `tests shader` from the sources under");
      Ada.Text_IO.Put_Line
        (Handle,
         "--  src/shaders. Do not edit: edit the shader, compile it, and");
      Ada.Text_IO.Put_Line
        (Handle, "--  run the tool again.");
      Ada.Text_IO.Put_Line (Handle, "--");
      Ada.Text_IO.Put_Line
        (Handle,
         "--  The digest below is of the shader source these words were");
      Ada.Text_IO.Put_Line
        (Handle,
         "--  compiled from. The release checklist compares it against the");
      Ada.Text_IO.Put_Line
        (Handle,
         "--  source in the tree, so a shader that has been edited and not");
      Ada.Text_IO.Put_Line
        (Handle, "--  recompiled is caught rather than quietly stale.");
      Ada.Text_IO.Put_Line (Handle, "--");
      Ada.Text_IO.Put_Line
        (Handle, "--  Task safety: constants, readable from any task.");
      Ada.Text_IO.Put_Line (Handle, "package Model_Runner.Shaders is");
      Ada.Text_IO.New_Line (Handle);
      Ada.Text_IO.Put_Line
        (Handle, "   type Word_Array is array (Positive range <>) of");
      Ada.Text_IO.Put_Line (Handle, "     Interfaces.Unsigned_32;");
      Ada.Text_IO.New_Line (Handle);
      Ada.Text_IO.Put_Line
        (Handle, "   --  Digest of src/shaders/row_product.comp when these");
      Ada.Text_IO.Put_Line (Handle, "   --  words were made from it.");
      Ada.Text_IO.Put_Line
        (Handle,
         "   Row_Product_Digest : constant Interfaces.Unsigned_64 :=");
      Ada.Text_IO.Put_Line
        (Handle, "     16#" & Hex (Digest) & "#;");
      Ada.Text_IO.New_Line (Handle);
      Ada.Text_IO.Put_Line
        (Handle,
         "   --  One row of a matrix against one vector, per invocation.");
      Ada.Text_IO.Put_Line
        (Handle, "   Row_Product : constant Word_Array :=");

      declare
         Words : constant Stream_Element_Offset := Last / 4;
         Column : Natural := 0;
      begin
         Ada.Text_IO.Put (Handle, "     [");

         for Index in 1 .. Words loop
            declare
               At_Byte : constant Stream_Element_Offset := (Index - 1) * 4 + 1;

               Value : constant Interfaces.Unsigned_32 :=
                 Interfaces.Unsigned_32 (Room (At_Byte))
                 or Interfaces.Shift_Left
                      (Interfaces.Unsigned_32 (Room (At_Byte + 1)), 8)
                 or Interfaces.Shift_Left
                      (Interfaces.Unsigned_32 (Room (At_Byte + 2)), 16)
                 or Interfaces.Shift_Left
                      (Interfaces.Unsigned_32 (Room (At_Byte + 3)), 24);

               Text : constant String := "16#" & Hex (Value) & "#";
            begin
               if Column = 0 then
                  if Index > 1 then
                     Ada.Text_IO.Put_Line (Handle, "");
                     Ada.Text_IO.Put (Handle, "      ");
                  end if;
               end if;

               Ada.Text_IO.Put (Handle, Text);

               --  The separator goes before the next word rather than after
               --  this one when the line ends here, because a comma and a
               --  space at the end of a line is a trailing space, and the
               --  gate refuses a build that leaves style warnings behind.
               --
               --  It wrote them for as long as it had existed -- five
               --  hundred and seventeen of them in the file it produces --
               --  and nothing said so, because a warning is only reported
               --  when a unit is compiled and this one had not been since
               --  the switch was turned on.
               Column := Column + 1;
               if Column = 5 then
                  Column := 0;
               end if;

               if Index < Words and then Column /= 0 then
                  Ada.Text_IO.Put (Handle, ", ");
               elsif Index < Words then
                  Ada.Text_IO.Put (Handle, ",");
               end if;
            end;
         end loop;

         Ada.Text_IO.Put_Line (Handle, "];");
      end;

      Ada.Text_IO.New_Line (Handle);
      Ada.Text_IO.Put_Line (Handle, "end Model_Runner.Shaders;");
      Ada.Text_IO.Close (Handle);

      Written := True;
   exception
      when others =>
         if Ada.Text_IO.Is_Open (Handle) then
            Ada.Text_IO.Close (Handle);
         end if;
         Written := False;
   end Write_Shader;

end Shader_Generation;
