with Ada.Numerics.Elementary_Functions;
with Ada.Text_IO;

with AUnit.Assertions;

with Interfaces;

with Model_Runner.Backend;
with Model_Runner.Backend.CPU;
with Model_Runner.Backend.Device;
with Model_Runner.Localization;
with Model_Runner.Cancellation;
with Model_Runner.Bytes;
with Model_Runner.Errors;
with Model_Runner.GGUF;
with Model_Runner.Numerics;
with Model_Runner.Platform;
with Model_Runner.Platform.Device;
with Model_Runner.Platform.Device.Products;
with Model_Runner.Tensors;

with Fixtures;

package body Tests.Backend_Cases is

   use AUnit.Assertions;
   use type Model_Runner.Bytes.Byte_Array_Access;
   use type Model_Runner.Errors.Error_Code;
   use type Model_Runner.Numerics.Element_Count;
   use type Model_Runner.Numerics.Real;
   use type Model_Runner.Bytes.Byte_Count;
   use type Model_Runner.Tensors.Real_Array_Access;

   package B renames Model_Runner.Bytes;
   package CPU renames Model_Runner.Backend.CPU;
   package E renames Model_Runner.Errors;
   package G renames Model_Runner.GGUF;
   package N renames Model_Runner.Numerics;
   package T renames Model_Runner.Tensors;
   package Devices renames Model_Runner.Platform.Device;
   package Products renames Model_Runner.Platform.Device.Products;

   Rows    : constant N.Element_Count := 37;
   Columns : constant N.Element_Count := 24;

   --  Build a float32 weight view over freshly generated bytes.
   procedure Make_Weight
     (Storage : out B.Byte_Array_Access;
      Weight  : out T.View)
   is
      Values : constant N.Real_Array :=
        Fixtures.Sequence (Rows * Columns, 4321, 1.0);
      Bytes  : constant B.Byte_Array := Fixtures.Encode_F32 (Values);
      Status : E.Error_Info;
   begin
      B.Allocate (Bytes'Length, Storage);
      Storage.all := Bytes;
      T.Make (G.Type_F32, Rows, Columns, Storage, 0, Weight, Status);
      Assert (E.Is_Ok (Status), "weight view could not be built");
   end Make_Weight;

   --  The partition covers every row exactly once, for every worker count.
   procedure Partition_Covers_Rows (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      for Total in N.Element_Count range 0 .. 40 loop
         --  Share counts, not worker counts: a job is cut into one more
         --  piece than there are workers, because the submitting task takes
         --  one. The top of that range is one past the top of this one.
         for Team in CPU.Share_Count range 1 .. 9 loop
            declare
               Seen : array (N.Element_Count range 0 .. 40) of Natural :=
                 [others => 0];
            begin
               for Index in CPU.Share_Count range 1 .. Team loop
                  declare
                     First, Last : N.Element_Count;
                  begin
                     CPU.Partition (Total, Team, Index, First, Last);
                     if First <= Last then
                        Assert (Last < Total,
                                "partition ran past the last row");
                        for Row in First .. Last loop
                           Seen (Row) := Seen (Row) + 1;
                        end loop;
                     end if;
                  end;
               end loop;

               for Row in N.Element_Count range 0 .. Total - 1 loop
                  Assert (Seen (Row) = 1,
                          "row" & N.Element_Count'Image (Row)
                          & " was covered" & Natural'Image (Seen (Row))
                          & " times with" & CPU.Share_Count'Image (Team)
                          & " workers");
               end loop;
            end;
         end loop;
      end loop;

      --  The largest share count there is, which is one past the largest
      --  worker count and is reached whenever a pool is opened with the
      --  maximum number of workers. Nothing else in this file goes near it.
      declare
         Total : constant N.Element_Count := 200;
         Seen  : array (0 .. 199) of Natural := [others => 0];
         First, Last : N.Element_Count;
      begin
         for Index in CPU.Share_Count'Range loop
            CPU.Partition (Total, CPU.Share_Count'Last, Index, First, Last);
            if First <= Last then
               for Row in First .. Last loop
                  Seen (Natural (Row)) := Seen (Natural (Row)) + 1;
               end loop;
            end if;
         end loop;

         for Row in Seen'Range loop
            Assert (Seen (Row) = 1,
                    "row" & Natural'Image (Row) & " covered"
                    & Natural'Image (Seen (Row)) & " times with"
                    & CPU.Share_Count'Image (CPU.Share_Count'Last)
                    & " shares");
         end loop;
      end;

   end Partition_Covers_Rows;

   --  A parallel product equals the serial one exactly, for every worker
   --  count. This is the property that makes changing --threads safe.
   procedure Parallel_Matches_Serial
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Status  : E.Error_Info;
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);

      declare
         Input : constant N.Real_Array := Fixtures.Sequence (Columns, 99, 1.0);
      begin
         Vector.all := Input;
      end;

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      for Team in CPU.Worker_Count range 1 .. 6 loop
         declare
            Pool     : aliased CPU.Pool (Team);
            Parallel : T.Real_Array_Access;
         begin
            T.Allocate (Rows, Parallel);
            CPU.Open (Pool);
            Assert (CPU.Is_Open (Pool), "pool did not open");
            Assert (CPU.Worker_Total (Pool) = Team, "wrong worker count");

            CPU.Mat_Vec (Pool, Weight, Vector, Parallel, Status);
            Assert (E.Is_Ok (Status),
                    "parallel product failed with"
                    & CPU.Worker_Count'Image (Team) & " workers: "
                    & E.Error_Code'Image (Status.Code));

            for Row in 0 .. Rows - 1 loop
               Assert (Parallel.all (Row) = Serial.all (Row),
                       "row" & N.Element_Count'Image (Row)
                       & " differs with" & CPU.Worker_Count'Image (Team)
                       & " workers");
            end loop;

            CPU.Close (Pool);
            T.Free (Parallel);
         end;
      end loop;

      T.Free (Vector);
      T.Free (Serial);
      B.Free (Storage);
   end Parallel_Matches_Serial;

   --  More workers than rows is legal: the surplus workers get nothing and the
   --  result is still complete.
   procedure More_Workers_Than_Rows
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Wide    : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (CPU.Worker_Count (Rows + 5));
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);
      T.Allocate (Rows, Wide);
      Vector.all := Fixtures.Sequence (Columns, 99, 1.0);

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      CPU.Mat_Vec (Pool, Weight, Vector, Wide, Status);
      Assert (E.Is_Ok (Status), "oversized pool failed");

      for Row in 0 .. Rows - 1 loop
         Assert (Wide.all (Row) = Serial.all (Row),
                 "row" & N.Element_Count'Image (Row)
                 & " differs when workers outnumber rows");
      end loop;

      CPU.Close (Pool);
      T.Free (Vector);
      T.Free (Serial);
      T.Free (Wide);
      B.Free (Storage);
   end More_Workers_Than_Rows;

   --  A closed pool rejects work rather than queueing it, and closing twice is
   --  harmless.
   procedure Closed_Pool_Rejects (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Target  : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (3);
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Target);
      Vector.all := Fixtures.Sequence (Columns, 5, 1.0);

      CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
      Assert (E.Is_Ok (Status), "first product failed");

      CPU.Close (Pool);
      Assert (not CPU.Is_Open (Pool), "a closed pool reported itself open");

      CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
      Assert (Status.Code = E.Backend_Closed,
              "a closed pool accepted work: " & E.Error_Code'Image (Status.Code));

      --  Closing twice must be harmless.
      CPU.Close (Pool);
      Assert (not CPU.Is_Open (Pool), "a second close changed the state");

      T.Free (Vector);
      T.Free (Target);
      B.Free (Storage);
   end Closed_Pool_Rejects;

   --  A pool is reusable: many jobs run through the same workers, and no task
   --  is created per job.
   procedure Pool_Is_Reused (T2 : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Target  : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (4);
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);
      T.Allocate (Rows, Target);
      Vector.all := Fixtures.Sequence (Columns, 17, 1.0);

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      for Round in 1 .. 50 loop
         Target.all := [others => 0.0];
         CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
         Assert (E.Is_Ok (Status),
                 "round" & Integer'Image (Round) & " failed");
         for Row in 0 .. Rows - 1 loop
            Assert (Target.all (Row) = Serial.all (Row),
                    "round" & Integer'Image (Round) & " differed");
         end loop;
      end loop;

      CPU.Close (Pool);
      T.Free (Vector);
      T.Free (Serial);
      T.Free (Target);
      B.Free (Storage);
   end Pool_Is_Reused;

   --  A pool that is created and then never used must still terminate. It
   --  does not, if its workers are left waiting for the call that binds them:
   --  the frame that declared the pool would wait for them forever. This test
   --  hangs rather than fails when that regresses, which is the only way the
   --  condition can be observed.
   procedure Unused_Pool_Terminates
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      for Team in CPU.Worker_Count range 1 .. 4 loop
         declare
            Idle : CPU.Pool (Team);
         begin
            --  Deliberately no work and no Open: this is the shape a command
            --  that fails while loading its model leaves behind.
            Assert (CPU.Worker_Total (Idle) = Team, "wrong worker count");
         end;
      end loop;

      --  A pool that is closed without ever running work must also terminate.
      declare
         Idle : CPU.Pool (3);
      begin
         CPU.Close (Idle);
         Assert (not CPU.Is_Open (Idle), "a closed pool reported itself open");
      end;
   end Unused_Pool_Terminates;

   --  Capabilities report what the backend actually implements.
   procedure Capabilities_Reported (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Single : constant Model_Runner.Backend.Capabilities := CPU.Describe (1);
      Many   : constant Model_Runner.Backend.Capabilities := CPU.Describe (4);
   begin
      Assert (Model_Runner.Backend.Backend_Name (Single.Kind) = "cpu",
              "wrong backend name");
      --  Determinism was a field here and is not any more: it could only
      --  ever be True, and a flag with one value documents nothing. What it
      --  claimed is tested where it can fail, by generating the same text at
      --  one worker and at four.
      Assert (not Single.Supports_Parallel,
              "one worker was reported as parallel");
      Assert (Many.Supports_Parallel, "many workers were reported as serial");
      Assert (Many.Max_Workers = CPU.Max_Workers, "wrong worker maximum");

      --  Only the formats with a decoder are advertised.
      Assert (Model_Runner.Backend.Supports (Single, G.Type_F32), "F32");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q4_K), "Q4_K");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q6_K), "Q6_K");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q2_K),
              "Q2_K is implemented but not advertised");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_BF16),
              "BF16 is implemented but not advertised");
   end Capabilities_Reported;

   ----------------------------------
   -- Device_Reports_What_It_Reads --
   ----------------------------------

   --  What the device backend says it can do, against what it does.
   --
   --  A capability record nobody asks is a record that can be wrong for a
   --  year, and this one is asked per tensor while a model loads: a format
   --  claimed here and not decoded by the shader is a model accepted and
   --  computed wrongly, which is worse than a model refused.
   procedure Device_Reports_What_It_Reads
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Said : constant Model_Runner.Backend.Capabilities :=
        Model_Runner.Backend.Device.Describe;
   begin
      Assert (Model_Runner.Backend.Backend_Name (Said.Kind) = "device",
              "wrong backend name");

      --  Every format the program reads, and nothing else. The shader used
      --  to decode three of the fifteen and now decodes all of them, so the
      --  two halves of this are the same statement said twice: what is
      --  claimed must be supported, and what is supported must be claimed.
      --
      --  The second half is the one that matters. A format claimed here and
      --  not decoded takes a model past the loader's check and into the
      --  shader, which reads its bytes as something they are not -- a wrong
      --  answer rather than a refusal, and nothing downstream can tell.
      --  Q8_1 and Q8_K are the two the parser recognizes and no kernel in
      --  this program decodes; they are refused before any backend is asked.
      for Format in G.Tensor_Type loop
         Assert (Model_Runner.Backend.Supports (Said, Format)
                 = G.Is_Supported (Format),
                 "the device backend "
                 & (if Model_Runner.Backend.Supports (Said, Format)
                    then "claims " & G.Type_Name (Format)
                         & ", which this program does not read"
                    else "disclaims " & G.Type_Name (Format)
                         & ", which the shader has a branch for"));
      end loop;

      Assert (Said.Supports_Matrix_Vector,
              "the device backend disclaims the one operation it is");
      Assert (Said.Supports_Batched,
              "the device backend disclaims batching, which its shader "
              & "carries");
      Assert (not Said.Supports_Parallel,
              "the device backend claims a pool it has none of");
      Assert (Said.Max_Workers = 1, "wrong worker maximum");
   end Device_Reports_What_It_Reads;

   ---------------------------------
   -- Device_Refuses_What_It_Must --
   ---------------------------------

   --  Every refusal the device backend can make, made.
   --
   --  These are the paths a model file can reach and a test rarely does: no
   --  device open, a format the shader has no branch for, and shapes that do
   --  not describe a product. None of them needs a device -- what is being
   --  checked is that they are answered before one is asked for -- so this
   --  runs the same on a machine with no device at all, which is where a
   --  refusal being wrong would otherwise never show.
   procedure Device_Refuses_What_It_Must
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      --  Every refusal below is rendered as well as identified, because a
      --  code is not a diagnostic until somebody can read it. Three of these
      --  named a message whose text asks for a parameter the site never
      --  attached, and a message that cannot be rendered comes out as its
      --  own key in angle brackets: MR-LIFE-0001 reached a user as
      --  <error.lifecycle.invalid_state> for as long as the backend existed.
      Words : Model_Runner.Localization.Catalog;

      procedure Reads (Status : E.Error_Info; Which : String) is
         Shown : constant String :=
           Model_Runner.Localization.Describe (Words, Status);
      begin
         Assert (Shown'Length > 0, Which & " rendered as nothing");
         Assert (Shown (Shown'First) /= '<',
                 Which & " did not render: " & Shown);
      end Reads;

      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Status  : E.Error_Info;

      Vector : T.Real_Array_Access;
      Room   : T.Real_Array_Access;

      --  A vector as wide as the packed matrix below, which the two-element
      --  one is not.
      Wide_Vector : T.Real_Array_Access;

      Was_Open : constant Boolean := Model_Runner.Backend.Device.Is_Ready;
   begin
      Model_Runner.Localization.Open
        (Words, Model_Runner.Platform.Catalog_Path, "en");
      Assert (Model_Runner.Localization.Is_Ready (Words),
              "the catalog would not open");

      --  Closed, whatever the machine has. A test that only refuses on a
      --  machine without a device is a test that says nothing on the one
      --  machine that runs this backend.
      Model_Runner.Backend.Device.Close;

      B.Allocate (16, Storage);
      Storage.all := [others => 0];
      T.Make (G.Type_F32, 2, 2, Storage, 0, Weight, Status);
      Assert (E.Is_Ok (Status), "weight view could not be built");

      T.Allocate (2, Vector);
      T.Allocate (2, Room);

      Model_Runner.Backend.Device.Dispatch (Weight, Vector, Room, Status);
      Assert (Status.Code = E.Backend_Closed,
              "a product on no device was not refused as a closed backend");
      Reads (Status, "a product on no device");

      Model_Runner.Backend.Device.Dispatch_Batch
        (Weight, Vector, 1, Room, Status);
      Assert (Status.Code = E.Backend_Closed,
              "a batch on no device was not refused as a closed backend");

      --  And with a device, if there is one: the refusals that come after
      --  the state check.
      declare
         Ready : Boolean;
      begin
         Model_Runner.Backend.Device.Open (Ready);

         if Ready then
            declare
               Packed : B.Byte_Array_Access;
               Other  : T.View;
            begin
               --  A packed format the shader used to have no branch
               --  for. This case asserted the refusal: Q4_1 was decoded by
               --  every other backend and not by this one, so a caller met
               --  Backend_Capability_Missing here. The shader now has a
               --  branch per format, so the same call has to succeed, and
               --  that is what is checked -- the refusal it replaced cannot
               --  be reached from outside at all any more, because a view
               --  will not hold a format the program does not decode and
               --  the device decodes every format it does.
               --
               --  Whether the answer is right is the per-format test's
               --  business; what this holds is that the request is taken.
               B.Allocate (40, Packed);
               Packed.all := [others => 0];
               T.Make (G.Type_Q4_1, 2, 32, Packed, 0, Other, Status);
               Assert (E.Is_Ok (Status), "packed view could not be built");

               --  Wide enough for the matrix, because a request whose
               --  shapes do not match is refused for that first and would
               --  say nothing about the format.
               T.Allocate (32, Wide_Vector);
               Model_Runner.Backend.Device.Dispatch
                 (Other, Wide_Vector, Room, Status);
               Assert (E.Is_Ok (Status),
                       "a packed matrix the shader now decodes was refused: "
                       & E.Error_Code'Image (Status.Code));

               T.Free (Wide_Vector);
               B.Free (Packed);
            end;

            --  Nothing to multiply.
            Model_Runner.Backend.Device.Dispatch (Weight, null, Room, Status);
            Assert (Status.Code = E.Tensor_Shape_Mismatch,
                    "a product with no vector was not refused as a shape");
            Reads (Status, "a product with no vector");

            Model_Runner.Backend.Device.Dispatch (Weight, Vector, null, Status);
            Assert (Status.Code = E.Tensor_Shape_Mismatch,
                    "a product with nowhere to put it was not refused as a "
                    & "shape");

            --  A batch of none, which is not a batch.
            Model_Runner.Backend.Device.Dispatch_Batch
              (Weight, Vector, 0, Room, Status);
            Assert (Status.Code = E.Tensor_Shape_Mismatch,
                    "a batch of no vectors was not refused as a shape");

            --  A batch of two through storage that holds one.
            Model_Runner.Backend.Device.Dispatch_Batch
              (Weight, Vector, 2, Room, Status);
            Assert (Status.Code = E.Tensor_Shape_Mismatch,
                    "a batch longer than its storage was not refused as a "
                    & "shape");

            --  And one that is right, so that the refusals above are known
            --  to be refusals of what they name rather than of everything.
            Model_Runner.Backend.Device.Dispatch (Weight, Vector, Room, Status);
            Assert (E.Is_Ok (Status),
                    "a product this backend can do was refused: "
                    & E.Error_Code'Image (Status.Code));
         end if;
      end;

      Model_Runner.Localization.Close (Words);

      T.Free (Vector);
      T.Free (Room);
      B.Free (Storage);

      --  Left as it was found. Another test may have a device open and this
      --  one has just closed it.
      if not Was_Open then
         Model_Runner.Backend.Device.Close;
      end if;
   end Device_Refuses_What_It_Must;

   ---------------------------------------
   -- Device_Decodes_Every_Format_It_Claims --
   ---------------------------------------

   --  Every format the shader decodes, against the processor's own decoder.
   --
   --  The shader carries a branch per format and each was written from the
   --  Ada decoder in Model_Runner.Quantization -- fifteen transcriptions of
   --  bit layouts, where a shift by the wrong amount, a sub-block scale read
   --  from the wrong byte or a level table off by one produces an answer
   --  that is merely wrong. Nothing downstream can tell a slightly wrong
   --  weight from a right one, so the check has to be here, at the one place
   --  the two decoders can be pointed at the same bytes.
   --
   --  Against the CPU backend rather than against stated values, because
   --  what is being checked is that the two agree: the values a format can
   --  hold are the format's business, and both sides are asked for the same
   --  ones.
   --
   --  Both widths matter. A batch of one and a batch of ten take different
   --  paths through the shader -- the second runs it twice with a different
   --  first vector -- and a decode that ignored the base offset would pass
   --  the first and fail the second.
   procedure Device_Decodes_Every_Format_It_Claims
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      --  The processor side of every comparison here multiplies in binary32,
      --  because the device does and has no other way: a processor that
      --  quantized its activations would differ from the shader by the
      --  arithmetic rather than by the layout, which is what this asks
      --  about. Restored at the end, since the flag belongs to the program
      --  and not to this test.
      Held : constant Boolean := CPU.Integer_Activations;

      Ready : Boolean;

      --  A whole number of super-blocks, which the k-quants need and the
      --  thirty-two element formats are happy with.
      Wide : constant N.Element_Count := 256;
      Tall : constant N.Element_Count := 12;

      Batch : constant := 10;

      Status : E.Error_Info;

      --  What a format is called, what encodes it, and nothing else: the
      --  loop below is the same for all fifteen.
      type Case_Kind is (Kind_F32, Kind_F16, Kind_BF16,
                         Kind_Q4_0, Kind_Q4_1, Kind_Q5_0, Kind_Q5_1,
                         Kind_Q8_0, Kind_IQ4_NL,
                         Kind_Q2_K, Kind_Q3_K, Kind_Q4_K, Kind_Q5_K,
                         Kind_Q6_K, Kind_IQ4_XS);

      function Format_Of (Which : Case_Kind) return G.Tensor_Type
      is (case Which is
             when Kind_F32    => G.Type_F32,
             when Kind_F16    => G.Type_F16,
             when Kind_BF16   => G.Type_BF16,
             when Kind_Q4_0   => G.Type_Q4_0,
             when Kind_Q4_1   => G.Type_Q4_1,
             when Kind_Q5_0   => G.Type_Q5_0,
             when Kind_Q5_1   => G.Type_Q5_1,
             when Kind_Q8_0   => G.Type_Q8_0,
             when Kind_IQ4_NL => G.Type_IQ4_NL,
             when Kind_Q2_K   => G.Type_Q2_K,
             when Kind_Q3_K   => G.Type_Q3_K,
             when Kind_Q4_K   => G.Type_Q4_K,
             when Kind_Q5_K   => G.Type_Q5_K,
             when Kind_Q6_K   => G.Type_Q6_K,
             when Kind_IQ4_XS => G.Type_IQ4_XS);

      function Encoded (Which : Case_Kind; Values : N.Real_Array)
                        return B.Byte_Array
      is (case Which is
             when Kind_F32    => Fixtures.Encode_F32 (Values),
             when Kind_F16    => Fixtures.Encode_F16 (Values),
             when Kind_BF16   => Fixtures.Encode_BF16 (Values),
             when Kind_Q4_0   => Fixtures.Encode_Q4_0 (Values),
             when Kind_Q4_1   => Fixtures.Encode_Q4_1 (Values),
             when Kind_Q5_0   => Fixtures.Encode_Q5_0 (Values),
             when Kind_Q5_1   => Fixtures.Encode_Q5_1 (Values),
             when Kind_Q8_0   => Fixtures.Encode_Q8_0 (Values),
             when Kind_IQ4_NL => Fixtures.Encode_IQ4_NL (Values),
             when Kind_Q2_K   => Fixtures.Encode_Q2_K (Values),
             when Kind_Q3_K   => Fixtures.Encode_Q3_K (Values),
             when Kind_Q4_K   => Fixtures.Encode_Q4_K (Values),
             when Kind_Q5_K   => Fixtures.Encode_Q5_K (Values),
             when Kind_Q6_K   => Fixtures.Encode_Q6_K (Values),
             when Kind_IQ4_XS => Fixtures.Encode_IQ4_XS (Values));
   begin
      CPU.Use_Integer_Activations (False);
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready);

      if not Ready then
         Ada.Text_IO.Put_Line
           (Ada.Text_IO.Standard_Error,
            "note: no device decoded anything here");
         return;
      end if;

      for Which in Case_Kind loop
         declare
            Name : constant String := G.Type_Name (Format_Of (Which));

            Values : N.Real_Array (0 .. Wide * Tall - 1);

            Storage : B.Byte_Array_Access;
            Weight  : T.View;

            Vectors : T.Real_Array_Access;
            There   : T.Real_Array_Access;
            Here    : T.Real_Array_Access;
         begin
            --  A ramp that turns over rather than a constant: a constant
            --  matrix comes out right under a decoder that reads the same
            --  wrong byte for every element, which is the fixture that
            --  cannot fail.
            for Index in Values'Range loop
               Values (Index) :=
                 N.Real (Integer (Index) mod 61) * 0.031 - 0.9;
            end loop;

            declare
               Bytes : constant B.Byte_Array := Encoded (Which, Values);
            begin
               B.Allocate (Bytes'Length, Storage);
               Storage.all := Bytes;
            end;

            T.Make (Format_Of (Which), Tall, Wide, Storage, 0, Weight,
                    Status);
            Assert (E.Is_Ok (Status),
                    "a weight view in " & Name & " could not be built");

            T.Allocate (Wide * Batch, Vectors);
            T.Allocate (Tall * Batch, There);
            T.Allocate (Tall * Batch, Here);

            for Index in Vectors.all'Range loop
               Vectors.all (Index) :=
                 N.Real (Integer (Index) mod 29) * 0.07 - 1.0;
            end loop;

            --  One vector, then the whole batch, on each backend.
            for Count in 1 .. 2 loop
               declare
                  Many : constant Positive :=
                    (if Count = 1 then 1 else Batch);
                  Room : constant N.Element_Count :=
                    Tall * N.Element_Count (Many);
               begin
                  if Many = 1 then
                     Model_Runner.Backend.Device.Dispatch
                       (Weight, Vectors, There, Status);
                     Assert (E.Is_Ok (Status),
                             "the device refused " & Name & ": "
                             & E.Error_Code'Image (Status.Code));
                     Model_Runner.Backend.CPU.Dispatch
                       (null, Weight, Vectors, Here, Status);
                  else
                     Model_Runner.Backend.Device.Dispatch_Batch
                       (Weight, Vectors, N.Element_Count (Many), There,
                        Status);
                     Assert (E.Is_Ok (Status),
                             "the device refused a batch of " & Name & ": "
                             & E.Error_Code'Image (Status.Code));
                     Model_Runner.Backend.CPU.Dispatch_Batch
                       (null, Weight, Vectors,
                        N.Element_Count (Many), Here, Status);
                  end if;

                  Assert (E.Is_Ok (Status),
                          "the processor refused " & Name & ": "
                          & E.Error_Code'Image (Status.Code));

                  for Index in 0 .. Room - 1 loop
                     --  The device accumulates in binary32 and the processor
                     --  in binary64, so the two are held to a tolerance
                     --  rather than to each other's bits. The gap this
                     --  catches is a misread layout, which is not small.
                     --
                     --  Both in the floating-point arithmetic: the device
                     --  shader multiplies in binary32 and has no integer
                     --  path, so comparing it against a processor that
                     --  quantized its activations would compare two
                     --  arithmetics and call the difference a misread
                     --  layout. Set where the processor side is dispatched,
                     --  above.
                     Assert (abs (There.all (Index) - Here.all (Index))
                             < 1.0E-3,
                             "the device decoded " & Name
                             & " differently from the processor at "
                             & N.Element_Count'Image (Index)
                             & " with" & Positive'Image (Many)
                             & " vectors:"
                             & N.Real'Image (There.all (Index))
                             & " against" & N.Real'Image (Here.all (Index)));
                  end loop;
               end;
            end loop;

            T.Free (Vectors);
            T.Free (There);
            T.Free (Here);
            B.Free (Storage);
         end;
      end loop;

      Model_Runner.Backend.Device.Close;
      CPU.Use_Integer_Activations (Held);
   end Device_Decodes_Every_Format_It_Claims;

   --------------------------------------------
   -- Device_Gives_Up_On_One_That_Will_Not_Answer --
   --------------------------------------------

   --  A dispatch that outlasts the whole bound finishes the engine.
   --
   --  A device that has stopped answering keeps the buffers it was given
   --  and there is no way to take work back off it, so the engine stops
   --  rather than resetting a command buffer the device may still be
   --  reading. That path had never run: it needs a device that has stopped
   --  answering, and a suite cannot arrange one.
   --
   --  What it can arrange is a bound of no time at all. A caller who asks
   --  for no patience waits not at all, so the first product it asks for
   --  exceeds the bound however fast the device is -- which reaches the
   --  giving-up path with a device in perfect health, and is the only way
   --  to reach it on purpose.
   --
   --  The engine is unusable afterwards, which is the point: what is
   --  checked is that it stays that way, because a device that has been
   --  given up on and then used again is the fault this exists to prevent.
   procedure Device_Gives_Up_On_One_That_Will_Not_Answer
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Ready : Boolean;

      Wide : constant N.Element_Count := 64;
      Tall : constant N.Element_Count := 8;

      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Room    : T.Real_Array_Access;
      Status  : E.Error_Info;
   begin
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready, Patience => 0.0);

      if not Ready then
         Ada.Text_IO.Put_Line
           (Ada.Text_IO.Standard_Error,
            "note: no device was given up on here");
         return;
      end if;

      declare
         Values : constant N.Real_Array (0 .. Wide * Tall - 1) :=
           [others => 0.5];
         Bytes  : constant B.Byte_Array := Fixtures.Encode_F32 (Values);
      begin
         B.Allocate (Bytes'Length, Storage);
         Storage.all := Bytes;
      end;

      T.Make (G.Type_F32, Tall, Wide, Storage, 0, Weight, Status);
      Assert (E.Is_Ok (Status), "the weight view could not be built");

      T.Allocate (Wide, Vector);
      T.Allocate (Tall, Room);
      Vector.all := [others => 1.0];

      Model_Runner.Backend.Device.Dispatch (Weight, Vector, Room, Status);
      Assert (Status.Code = E.Backend_Device_Stalled,
              "a dispatch that outlasted the bound was reported as "
              & E.Error_Code'Image (Status.Code)
              & " rather than as a device that stopped answering");

      --  And it does not come back. An engine that gave up and then served
      --  the next product would be recording over a buffer it does not own.
      Model_Runner.Backend.Device.Dispatch (Weight, Vector, Room, Status);
      Assert (not E.Is_Ok (Status),
              "an engine that gave up on its device answered the next "
              & "product as though nothing had happened");

      T.Free (Vector);
      T.Free (Room);
      B.Free (Storage);

      --  Closed here rather than left, because every test after this one
      --  would otherwise meet an engine that has given up.
      Model_Runner.Backend.Device.Close;
   end Device_Gives_Up_On_One_That_Will_Not_Answer;

   -------------------------------------------
   -- Device_Stops_When_The_Caller_Asks --
   -------------------------------------------

   --  A product on the device answers a standing stop request.
   --
   --  Cancellation is checked between layers everywhere else in this
   --  program, and a layer on a device is a submission and a wait for it.
   --  The wait could not be interrupted, so it was the longest a stop
   --  request went unanswered -- and on a wider model or a longer batch than
   --  this machine runs, that is the whole of a layer. The wait is taken in
   --  slices now, and the token is asked between them.
   --
   --  What is checked here is the standing case, because it is the only one
   --  a test can arrange: a request arriving during a wait needs a wait long
   --  enough to arrive during, and a product that takes that long is not
   --  something a suite can conjure on demand. The standing case exercises
   --  the same path from the caller down to the engine; what it does not
   --  reach is the loop itself.
   --
   --  Answered before the device is touched, which is also the honest
   --  answer: a caller who has already asked to stop should not have work
   --  uploaded for them.
   procedure Device_Stops_When_The_Caller_Asks
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Ready : Boolean;

      Wide : constant N.Element_Count := 64;
      Tall : constant N.Element_Count := 8;

      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Room    : T.Real_Array_Access;
      Status  : E.Error_Info;

      Stop : aliased Model_Runner.Cancellation.Token;
   begin
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready);

      if not Ready then
         Ada.Text_IO.Put_Line
           (Ada.Text_IO.Standard_Error,
            "note: no device was asked to stop here");
         return;
      end if;

      declare
         Values : constant N.Real_Array (0 .. Wide * Tall - 1) :=
           [others => 0.5];
         Bytes  : constant B.Byte_Array := Fixtures.Encode_F32 (Values);
      begin
         B.Allocate (Bytes'Length, Storage);
         Storage.all := Bytes;
      end;

      T.Make (G.Type_F32, Tall, Wide, Storage, 0, Weight, Status);
      Assert (E.Is_Ok (Status), "the weight view could not be built");

      T.Allocate (Wide, Vector);
      T.Allocate (Tall, Room);
      Vector.all := [others => 1.0];

      --  Without a request first, so that what follows is the request's
      --  doing and not the product's.
      Model_Runner.Backend.Device.Dispatch
        (Weight, Vector, Room, Status, Stop'Unchecked_Access);
      Assert (E.Is_Ok (Status),
              "a product with no request standing was refused: "
              & E.Error_Code'Image (Status.Code));

      Stop.Request;
      Model_Runner.Backend.Device.Dispatch
        (Weight, Vector, Room, Status, Stop'Unchecked_Access);
      Assert (Status.Code = E.Generation_Cancelled,
              "a standing request did not stop a product on the device: "
              & E.Error_Code'Image (Status.Code));

      --  And a request that arrives while the device is working, which is
      --  the case the slicing exists for and the one above does not reach:
      --  a request already standing is answered before anything is
      --  submitted, so it never gets near the loop.
      --
      --  Two things make this reliable rather than a race. The slices are a
      --  nanosecond, so a wait times out however fast the device is and the
      --  loop goes round to ask the token -- without that, seeing the
      --  request would depend on the product outlasting twenty
      --  milliseconds, which is a test that passes on one machine. And the
      --  matrix is four million elements, so the product takes long enough
      --  for another task to have run by the time it is done.
      declare
         During : aliased Model_Runner.Cancellation.Token;

         Big_Wide : constant N.Element_Count := 2048;
         Big_Tall : constant N.Element_Count := 2048;

         Big_Storage : B.Byte_Array_Access;
         Big_Weight  : T.View;
         Big_Vector  : T.Real_Array_Access;
         Big_Room    : T.Real_Array_Access;

      begin
         Model_Runner.Backend.Device.Close;
         Model_Runner.Backend.Device.Open (Ready, Slice => 0.000_000_001);
         Assert (Ready, "the device would not reopen with a tiny slice");

         --  Filled rather than encoded, because encoding four million
         --  values means a value array and a byte array of them both alive
         --  at once, and thirty-two megabytes of that does not belong on a
         --  stack. What the bytes say does not matter here; how many of
         --  them there are does.
         B.Allocate
           (Model_Runner.Bytes.Byte_Count (Big_Wide * Big_Tall) * 4,
            Big_Storage);
         Assert (Big_Storage /= null, "no room for the large matrix");
         Big_Storage.all := [others => 60];

         T.Make (G.Type_F32, Big_Tall, Big_Wide, Big_Storage, 0, Big_Weight,
                 Status);
         Assert (E.Is_Ok (Status), "the large weight view could not be built");

         T.Allocate (Big_Wide, Big_Vector);
         T.Allocate (Big_Tall, Big_Room);
         Big_Vector.all := [others => 1.0];

         --  The asking task is declared here rather than above, so that
         --  its delay starts beside the dispatch instead of before the
         --  sixteen megabytes are allocated and filled. Started earlier, it
         --  had always fired by the time the product began -- which is the
         --  standing case again, and the slice counter below is what caught
         --  that rather than a green test hiding it.
         declare
            task Asks;

            task body Asks is
            begin
               delay 0.000_1;
               During.Request;
            end Asks;
         begin
            Model_Runner.Backend.Device.Dispatch
              (Big_Weight, Big_Vector, Big_Room, Status,
               During'Unchecked_Access);
         end;

         Assert (Status.Code = E.Generation_Cancelled,
                 "a request made while the device was working was not seen "
                 & "between slices of the wait: "
                 & E.Error_Code'Image (Status.Code));

         --  And it was seen there rather than by the check before anything
         --  is submitted. That check answers a request that was already
         --  standing, so a cancelled product proves nothing on its own:
         --  what proves it is that the wait went round more than once,
         --  which is the only place a request arriving later can be seen.
         Assert (Model_Runner.Backend.Device.Waited > 1,
                 "the product was cancelled without the wait going round, "
                 & "so the request was already standing and this says "
                 & "nothing about a request that arrives during a product");

         T.Free (Big_Vector);
         T.Free (Big_Room);
         B.Free (Big_Storage);
      end;

      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready);

      Model_Runner.Backend.Device.Dispatch_Batch
        (Weight, Vector, 1, Room, Status, Stop'Unchecked_Access);
      Assert (Status.Code = E.Generation_Cancelled,
              "a standing request did not stop a batch on the device: "
              & E.Error_Code'Image (Status.Code));

      --  And a caller that passes no token is not stopped by somebody
      --  else's, which is what a null reference has to mean.
      Model_Runner.Backend.Device.Dispatch (Weight, Vector, Room, Status);
      Assert (E.Is_Ok (Status),
              "a product with no token was refused while a request stood "
              & "elsewhere: " & E.Error_Code'Image (Status.Code));

      T.Free (Vector);
      T.Free (Room);
      B.Free (Storage);
      Model_Runner.Backend.Device.Close;
   end Device_Stops_When_The_Caller_Asks;

   ------------------------------------------
   -- Device_Gives_Back_What_It_Cannot_Hold --
   ------------------------------------------

   --  A device given less memory than the matrices need keeps computing.
   --
   --  What it does instead of failing is give back the matrix wanted longest
   --  ago and upload the next in its place, which is slower and still right.
   --  Before this it did neither: it kept matrices until an allocation
   --  failed and then failed the product, so a model larger than the device
   --  was a run that stopped in the middle of a token.
   --
   --  Driven by opening the device with a budget rather than by finding a
   --  model too large for one, because the interesting case is the one no
   --  machine here can produce on demand.
   procedure Device_Gives_Back_What_It_Cannot_Hold
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      use type Interfaces.Unsigned_64;

      Ready : Boolean;

      Shapes  : constant := 6;
      Wide    : constant N.Element_Count := 64;
      Tall    : constant N.Element_Count := 16;

      --  Room for two of the six matrices, so every pass round the loop
      --  wants one that is not there.
      Each   : constant Interfaces.Unsigned_64 :=
        Interfaces.Unsigned_64 (Wide) * Interfaces.Unsigned_64 (Tall) * 4;
      Budget : constant Interfaces.Unsigned_64 := Each * 2;

      Held    : array (1 .. Shapes) of B.Byte_Array_Access;
      Views   : array (1 .. Shapes) of T.View;
      Wanted  : array (1 .. Shapes) of N.Real := [others => 0.0];

      Vector  : T.Real_Array_Access;
      Room    : T.Real_Array_Access;
      Status  : E.Error_Info;
   begin
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready, Budget);

      if not Ready then
         Ada.Text_IO.Put_Line
           (Ada.Text_IO.Standard_Error,
            "note: no device gave anything back here");
         return;
      end if;

      Assert (Model_Runner.Backend.Device.Given_Back = 0,
              "a device that has computed nothing has given something back");

      T.Allocate (Wide, Vector);
      T.Allocate (Tall, Room);
      Assert (Vector /= null and then Room /= null, "no room for the test");

      for Index in Vector.all'Range loop
         Vector.all (Index) := 1.0;
      end loop;

      --  Six matrices, each a different constant, so the answer says which
      --  one was multiplied by. A matrix given back and uploaded again has
      --  to come back the same or this says so.
      for Which in Held'Range loop
         declare
            Values : N.Real_Array (0 .. Wide * Tall - 1) :=
              [others => 0.0];
            Each_Value : constant N.Real :=
              N.Real (Which) * 0.25 - 0.125;
         begin
            Values := [others => Each_Value];
            declare
               Bytes : constant B.Byte_Array := Fixtures.Encode_F32 (Values);
            begin
               B.Allocate (Bytes'Length, Held (Which));
               Held (Which).all := Bytes;
            end;

            T.Make (G.Type_F32, Tall, Wide, Held (Which), 0, Views (Which),
                    Status);
            Assert (E.Is_Ok (Status), "a weight view could not be built");

            Wanted (Which) := Each_Value * N.Real (Wide);
         end;
      end loop;

      --  Three passes over all six, so that everything is asked for again
      --  after it has been given back.
      for Pass in 1 .. 3 loop
         for Which in Held'Range loop
            Model_Runner.Backend.Device.Dispatch
              (Views (Which), Vector, Room, Status);
            Assert (E.Is_Ok (Status),
                    "a product was refused for want of device memory: "
                    & E.Error_Code'Image (Status.Code));

            for Row in Room.all'Range loop
               Assert (abs (Room.all (Row) - Wanted (Which)) < 1.0E-3,
                       "a matrix came back different after being given back");
            end loop;
         end loop;
      end loop;

      --  It held what it could and gave back the rest, rather than holding
      --  everything or holding nothing.
      Assert (Model_Runner.Backend.Device.Resident > 0,
              "a device with room for two matrices held none");
      Assert (Model_Runner.Backend.Device.Given_Back > 0,
              "a device with room for two of six matrices gave none back");

      for Which in Held'Range loop
         B.Free (Held (Which));
      end loop;

      T.Free (Vector);
      T.Free (Room);
      Model_Runner.Backend.Device.Close;
   end Device_Gives_Back_What_It_Cannot_Hold;

   ---------------------------------------------
   -- Device_Reads_The_Host_Memory_When_Asked --
   ---------------------------------------------

   --  A device asked to read the weights where they lie gets the same
   --  answers as the processor, in every format the shader decodes and
   --  through both of the ways it is asked.
   --
   --  Two things have to hold and only one of them is the arithmetic. The
   --  other is the offset: a host pointer is aligned down to a page, so the
   --  buffer starts before the weights do and the shader is told how far in
   --  they begin. That offset is added to word indices for binary32 and to
   --  byte indices for the packed formats -- two different arithmetics, and
   --  the first version of this test exercised one of them.
   --
   --  The storage is deliberately large and the matrix deliberately in the
   --  middle of it. A device is handed whole pages, so a matrix within a
   --  page of either end of what this process owns is copied instead --
   --  which is what every matrix of a small fixture is, and why the
   --  conformance sweep cannot test this and says so.
   --
   --  Skipped where the device will not take a pointer at all, which is any
   --  device on most machines.
   procedure Device_Reads_The_Host_Memory_When_Asked
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Ready : Boolean;

      Wide  : constant N.Element_Count := 128;
      Tall  : constant N.Element_Count := 40;
      Batch : constant N.Element_Count := 11;

      --  Somewhere in the middle, and not on a boundary of anything: a page
      --  either side of the matrix and an offset that is not a multiple of
      --  a page, so the distance the shader is told about is not zero.
      Room_Bytes : constant B.Byte_Count := 1024 * 1024;
      At_Byte    : constant B.Byte_Count := 300_000;

      Storage : B.Byte_Array_Access;
      Status  : E.Error_Info;

      Vectors : T.Real_Array_Access;
      Here    : T.Real_Array_Access;
      There   : T.Real_Array_Access;

      Values : N.Real_Array (0 .. Wide * Tall - 1);

      Took : Natural := 0;

      --  The processor side multiplies in binary32 here, because the device
      --  it is compared against has no other arithmetic. Restored below.
      Held : constant Boolean := CPU.Integer_Activations;
   begin
      CPU.Use_Integer_Activations (False);
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready, Share_Host => True);

      if not Ready then
         return;
      end if;

      B.Allocate (Room_Bytes, Storage);
      Assert (Storage /= null, "no room for the test");
      Storage.all := [others => 0];

      T.Allocate (Wide * Batch, Vectors);
      T.Allocate (Tall * Batch, Here);
      T.Allocate (Tall * Batch, There);
      Assert (Vectors /= null and then Here /= null and then There /= null,
              "no room for the vectors");

      for Index in Vectors.all'Range loop
         Vectors.all (Index) :=
           N.Real (Index mod 13) * 0.125 - 0.4375;
      end loop;

      --  Awkward values rather than round ones: the packed formats round
      --  what they are given, and values a quantizer reproduces exactly
      --  would let a decoding fault pass unnoticed.
      for Index in Values'Range loop
         Values (Index) :=
           1.0 / N.Real (3 + Natural (Index) mod 89) - 0.037;
      end loop;

      for Format in 1 .. 3 loop
         declare
            Kind : constant G.Tensor_Type :=
              (case Format is
                 when 1 => G.Type_F32,
                 when 2 => G.Type_Q8_0,
                 when others => G.Type_Q4_0);

            Packed : constant B.Byte_Array :=
              (case Format is
                 when 1 => Fixtures.Encode_F32 (Values),
                 when 2 => Fixtures.Encode_Q8_0 (Values),
                 when others => Fixtures.Encode_Q4_0 (Values));

            Weight : T.View;
         begin
            Storage.all (Storage.all'First + At_Byte
                         .. Storage.all'First + At_Byte + Packed'Length - 1) :=
              Packed;

            T.Make (Kind, Tall, Wide, Storage, At_Byte, Weight, Status);
            Assert (E.Is_Ok (Status),
                    "the weight view could not be built for "
                    & G.Type_Name (Kind));

            --  One vector, and then a batch that is neither one dispatch's
            --  worth nor a whole number of them.
            for Batched in Boolean loop
               declare
                  Count : constant N.Element_Count :=
                    (if Batched then Batch else 1);
               begin
                  Here.all := [others => 0.0];
                  There.all := [others => 0.0];

                  if Batched then
                     CPU.Dispatch_Batch
                       (null, Weight, Vectors, Count, Here, Status);
                  else
                     CPU.Dispatch (null, Weight, Vectors, Here, Status);
                  end if;
                  Assert (E.Is_Ok (Status),
                          "the processor refused the product");

                  if Batched then
                     Model_Runner.Backend.Device.Dispatch_Batch
                       (Weight, Vectors, Count, There, Status);
                  else
                     Model_Runner.Backend.Device.Dispatch
                       (Weight, Vectors, There, Status);
                  end if;
                  Assert (E.Is_Ok (Status),
                          "a product on the host's own memory was refused: "
                          & E.Error_Code'Image (Status.Code));

                  for Index in 0 .. Tall * Count - 1 loop
                     declare
                        Want : constant N.Real :=
                          Here.all (Here.all'First + Index);
                        Got  : constant N.Real :=
                          There.all (There.all'First + Index);
                     begin
                        --  Binary32 against binary64 over 128 terms, on
                        --  values around a tenth: this is what that
                        --  arithmetic carries, and it is the same bound the
                        --  product test uses.
                        Assert (abs (Want - Got) < 1.0E-4,
                                "a matrix read where it lies disagrees with "
                                & "the processor in "
                                & G.Type_Name (Kind)
                                & (if Batched then " batched" else "")
                                & " at" & N.Element_Count'Image (Index)
                                & ":" & N.Real'Image (Want)
                                & " against" & N.Real'Image (Got));
                     end;
                  end loop;
               end;
            end loop;

            --  And it was read where it lies rather than quietly copied,
            --  which a correct answer alone would not show. This is the
            --  assertion the first version of the test did not make, and
            --  without it the whole thing passed while importing nothing.
            Assert (Model_Runner.Backend.Device.Imported > Took,
                    "a device asked to read " & G.Type_Name (Kind)
                    & " where it lies copied it instead");
            Took := Model_Runner.Backend.Device.Imported;
         end;
      end loop;

      Assert (Interfaces."=" (Model_Runner.Backend.Device.Resident_Bytes, 0),
              "a device reading the host's memory is holding bytes of its "
              & "own as well");

      T.Free (Vectors);
      T.Free (Here);
      T.Free (There);
      B.Free (Storage);
      Model_Runner.Backend.Device.Close;
      CPU.Use_Integer_Activations (Held);
   end Device_Reads_The_Host_Memory_When_Asked;

   ------------------------------------------
   -- Resident_Cache_Attends_As_A_Host_Does --
   ------------------------------------------

   --  The three the engine says as it generates -- reserve room, write a
   --  position, attend to what was written -- against a blend worked out
   --  here, in the open, on numbers small enough to check by hand.
   --
   --  This is the path both evaluators take. When it was said in one
   --  evaluator and not the other, a drafted run stopped agreeing with an
   --  undrafted one, and the difference was arithmetic rather than a
   --  refusal: nothing failed, the answer was merely other.
   procedure Resident_Cache_Attends_As_A_Host_Does
     (T_Case : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T_Case);

      --  One head, four wide, three positions. Small enough that the
      --  expected blend below is worked out rather than trusted.
      Head_Size  : constant N.Element_Count := 4;
      Positions  : constant N.Element_Count := 3;
      Room       : constant N.Element_Count := Head_Size * Positions;

      Ready : Boolean;
      Ok    : Boolean;

      Query : constant N.Real_Array (0 .. Head_Size - 1) :=
        [1.0, 0.0, 0.0, 0.0];

      --  Keys chosen so the first position scores highest and the third
      --  lowest, which makes a wrong ordering visible in the result.
      Keys : constant N.Real_Array (0 .. Room - 1) :=
        [2.0, 0.0, 0.0, 0.0,
         1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0];

      --  Values that name their position, so a blend says which positions
      --  it read and how much of each.
      Values : constant N.Real_Array (0 .. Room - 1) :=
        [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0];

      Blend : N.Real_Array (0 .. Head_Size - 1) := [others => 0.0];

      Scale : constant N.Real := 1.0;

      --  What the three scores come to once softened, worked out from
      --  exp (2), exp (1) and exp (0).
      Total : constant N.Real :=
        N.Real (Ada.Numerics.Elementary_Functions.Exp (2.0))
        + N.Real (Ada.Numerics.Elementary_Functions.Exp (1.0))
        + 1.0;
      Wanted : constant N.Real_Array (0 .. Head_Size - 1) :=
        [N.Real (Ada.Numerics.Elementary_Functions.Exp (2.0)) / Total,
         N.Real (Ada.Numerics.Elementary_Functions.Exp (1.0)) / Total,
         1.0 / Total,
         0.0];

      --  Loose enough for a device working in binary32 and for the online
      --  softmax rescaling its running total as it goes.
      Near : constant N.Real := 1.0e-4;
   begin
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready, Share_Host => False);

      if not Ready then
         --  A machine with no device says nothing here, as the other
         --  device cases do.
         return;
      end if;

      Model_Runner.Backend.Device.Reserve_Cache (Room * 2, Ok);

      if not Ok then
         --  A device that will not hold a cache is a slower run, not a
         --  wrong one; the engine falls back to the processor.
         Model_Runner.Backend.Device.Close;
         return;
      end if;

      Model_Runner.Backend.Device.Put_Cache (0, Keys, Ok);
      Assert (Ok, "a device that reserved room would not take the keys");

      --  The values follow the keys in the one buffer attention reads.
      Model_Runner.Backend.Device.Put_Cache (Room, Values, Ok);
      Assert (Ok, "a device that took the keys would not take the values");

      Model_Runner.Backend.Device.Attend
        (Query      => Query,
         Heads      => 1,
         Head_Size  => Natural (Head_Size),
         Value_Size => Natural (Head_Size),
         Group_Size => 1,
         First      => 0,
         Last       => Natural (Positions) - 1,
         K_Base     => 0,
         V_Base     => Natural (Room),
         KV_Width   => Natural (Head_Size),
         V_Width    => Natural (Head_Size),
         Scale      => Scale,
         Cap        => 0.0,
         Target     => Blend,
         Ok         => Ok);

      Assert (Ok, "a device holding the cache would not attend to it");

      for Index in Blend'Range loop
         Assert (abs (Blend (Index) - Wanted (Index)) <= Near,
                 "the device's blend differs from the one worked out here "
                 & "at component" & N.Element_Count'Image (Index));
      end loop;

      --  Reserving again for the same room is the engine's every-position
      --  case, and must neither refuse nor lose what is there.
      Model_Runner.Backend.Device.Reserve_Cache (Room * 2, Ok);
      Assert (Ok, "asking again for room a device already holds was "
              & "refused");

      Blend := [others => 0.0];
      Model_Runner.Backend.Device.Attend
        (Query      => Query,
         Heads      => 1,
         Head_Size  => Natural (Head_Size),
         Value_Size => Natural (Head_Size),
         Group_Size => 1,
         First      => 0,
         Last       => Natural (Positions) - 1,
         K_Base     => 0,
         V_Base     => Natural (Room),
         KV_Width   => Natural (Head_Size),
         V_Width    => Natural (Head_Size),
         Scale      => Scale,
         Cap        => 0.0,
         Target     => Blend,
         Ok         => Ok);

      Assert (Ok, "a device would not attend a second time");

      for Index in Blend'Range loop
         Assert (abs (Blend (Index) - Wanted (Index)) <= Near,
                 "a cache reserved a second time lost what was written to "
                 & "it at component" & N.Element_Count'Image (Index));
      end loop;

      Model_Runner.Backend.Device.Close;
   end Resident_Cache_Attends_As_A_Host_Does;

   -----------------------------------------------
   -- Recorded_Attention_Says_What_A_Call_Says --
   -----------------------------------------------

   --  Attention recorded into a sequence against attention submitted on its
   --  own, on the same cache with the same queries.
   --
   --  A sequence exists so that a layer's steps go over in one submission
   --  instead of several, and attention was the step that could not join
   --  one: while it was submitted alone the products either side of it
   --  could not be sent together. What has to be true before anything is
   --  built on that is that the recorded form computes the same thing, and
   --  a device is not a place to find that out by inspection.
   procedure Recorded_Attention_Says_What_A_Call_Says
     (T_Case : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T_Case);

      Heads     : constant := 4;
      Head_Size : constant := 8;
      Positions : constant := 5;

      Span : constant N.Element_Count := Heads * Head_Size;
      Room : constant N.Element_Count :=
        N.Element_Count (Positions) * Span;

      Held   : Devices.Inventory;
      Opened : Devices.Context;
      Engine : Products.Engine;

      Found : Boolean;
      Ready : Boolean;
      Ok    : Boolean;

      Cache : N.Real_Array (0 .. Room * 2 - 1);
      Query : N.Real_Array (0 .. Span - 1);

      Alone    : N.Real_Array (0 .. Span - 1) := [others => 0.0];
      Recorded : N.Real_Array (0 .. Span - 1) := [others => 0.0];

      Steps : Products.Sequence;
      Added : Boolean;

      Halted : Boolean;

      --  Both arms run the same kernel on the same device, so they should
      --  agree to the last bit; this leaves room for the two paths reaching
      --  it through different buffers rather than for different arithmetic.
      Near : constant N.Real := 1.0e-6;
   begin
      Devices.Open (Held, Found);

      if not Found or else Devices.Count (Held) = 0 then
         Devices.Close (Held);
         return;
      end if;

      Devices.Open (Opened, Held, 1, Ready);

      if not Ready then
         Devices.Close (Held);
         return;
      end if;

      Products.Open (Engine, Opened, Ready);

      if not Ready then
         Devices.Close (Opened);
         Devices.Close (Held);
         return;
      end if;

      --  Something with structure rather than a constant, so that a blend
      --  reading the wrong region says so.
      for Index in Cache'Range loop
         Cache (Index) := N.Real (Index mod 13) / 13.0 - 0.5;
      end loop;
      for Index in Query'Range loop
         Query (Index) := N.Real (Index mod 7) / 7.0 - 0.25;
      end loop;

      Products.Reserve (Engine, Cache'Length, Ok);

      if not Ok then
         Products.Close (Engine);
         Devices.Close (Opened);
         Devices.Close (Held);
         return;
      end if;

      Products.Put_Cache (Engine, 0, Cache, Ok);
      Assert (Ok, "the cache would not be written");

      Products.Attend_Resident
        (Engine, Query,
         Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
         Group_Size => 1, First => 0, Last => Positions - 1,
         K_Base => 0, V_Base => Natural (Room),
         KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
         Scale => 0.25, Cap => 0.0, Target => Alone, Ok => Ok);

      Assert (Ok, "attention on its own was refused");

      Products.Open_Sequence (Steps);
      Products.Add_Attention
        (Steps,
         Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
         Group_Size => 1, First => 0, Last => Positions - 1,
         K_Base => 0, V_Base => Natural (Room),
         KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
         Scale => 0.25, Cap => 0.0, Added => Added);

      Assert (Added, "a sequence would not take an attention step");
      Assert (Products.Length (Steps) = 1,
              "an attention step was taken and not counted");

      Products.Run (Engine, Steps, Query, 1, Recorded, Ok, Halted);

      Assert (Ok, "a sequence holding an attention step was refused");
      Assert (not Halted, "nothing asked it to stop");

      --  And the same attention reading its queries from the step before it
      --  instead of from the activation. A product whose result is exactly
      --  the queries stands in for the rotation the engine does on the
      --  processor: what matters here is that the queries never leave the
      --  device and the answer does not change.
      declare
         Identity : Model_Runner.Bytes.Byte_Array_Access;
         Through  : N.Real_Array (0 .. Span * 2 - 1) := [others => 0.0];
      begin
         Model_Runner.Bytes.Allocate
           (Model_Runner.Bytes.Byte_Count (Span * Span) * 4, Identity);
         Assert (Identity /= null, "no room for the matrix");

         Identity.all := [others => 0];
         for Row in 0 .. Span - 1 loop
            declare
               At_Byte : constant Model_Runner.Bytes.Byte_Count :=
                 Model_Runner.Bytes.Byte_Count (Row * Span + Row) * 4 + 1;
            begin
               Identity.all (At_Byte .. At_Byte + 3) :=
                 Model_Runner.Bytes.Put_F32 (1.0);
            end;
         end loop;

         Products.Open_Sequence (Steps);
         Products.Add_Product
           (Steps, Identity.all'Address,
            Model_Runner.Bytes.Byte_Count (Identity.all'Length),
            0, Products.Values_F32,
            Natural (Span), Natural (Span), Added);
         Assert (Added, "a sequence would not take the product");

         Products.Add_Attention
           (Steps,
            Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
            Group_Size => 1, First => 0, Last => Positions - 1,
            K_Base => 0, V_Base => Natural (Room),
            KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
            Scale => 0.25, Cap => 0.0, Added => Added, Chained => True);
         Assert (Added, "a sequence would not take a chained attention");

         Products.Run (Engine, Steps, Query, 1, Through, Ok, Halted);
         Assert (Ok, "a chained attention was refused");

         for Index in 0 .. Span - 1 loop
            Assert (abs (Alone (Index) - Through (Span + Index)) <= Near,
                    "attention reading queries it was handed differs from "
                    & "attention reading queries left where they were, at "
                    & "component" & N.Element_Count'Image (Index));
         end loop;

         --  A chained attention with nothing before it has nothing to read.
         Products.Open_Sequence (Steps);
         Products.Add_Attention
           (Steps,
            Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
            Group_Size => 1, First => 0, Last => Positions - 1,
            K_Base => 0, V_Base => Natural (Room),
            KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
            Scale => 0.25, Cap => 0.0, Added => Added, Chained => True);
         Assert (not Added,
                 "a chained attention with nothing to chain to was taken");

         Model_Runner.Bytes.Free (Identity);
      end;

      for Index in Alone'Range loop
         Assert (abs (Alone (Index) - Recorded (Index)) <= Near,
                 "recorded attention differs from attention submitted alone "
                 & "at component" & N.Element_Count'Image (Index));
      end loop;

      --  The call that carries its own cache takes a batch too, and must
      --  say what the resident one says for every position of it. Two
      --  positions, the second seeing one more than the first.
      declare
         Pair : N.Real_Array (0 .. Span * 2 - 1);
         Both : N.Real_Array (0 .. Span * 2 - 1) := [others => 0.0];
         Each : N.Real_Array (0 .. Span - 1) := [others => 0.0];
      begin
         Pair (0 .. Span - 1) := Query;
         Pair (Span .. Span * 2 - 1) := Query;

         Products.Attend
           (Engine, Cache, Pair,
            Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
            Group_Size => 1, First => 0, Last => Positions - 2,
            K_Base => 0, V_Base => Natural (Room),
            KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
            Scale => 0.25, Cap => 0.0, Target => Both, Ok => Ok,
            Positions => 2);

         Assert (Ok, "a batch through the call that carries its cache was "
                 & "refused");

         for Slot in 0 .. 1 loop
            Products.Attend
              (Engine, Cache, Query,
               Heads => Heads, Head_Size => Head_Size,
               Value_Size => Head_Size,
               Group_Size => 1, First => 0,
               Last => Positions - 2 + Slot,
               K_Base => 0, V_Base => Natural (Room),
               KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
               Scale => 0.25, Cap => 0.0, Target => Each, Ok => Ok);

            Assert (Ok, "one position of the pair was refused on its own");

            for Index in Each'Range loop
               Assert (abs (Each (Index)
                            - Both (N.Element_Count (Slot) * Span + Index))
                       <= Near,
                       "a batch of two differs from the two taken singly at "
                       & "position" & Integer'Image (Slot) & ", component"
                       & N.Element_Count'Image (Index));
            end loop;
         end loop;
      end;

      --  And a sequence recorded against a cache the engine does not hold
      --  is refused rather than run against whatever the binding last
      --  named, which would answer with the previous call's keys.
      Products.Close (Engine);
      Products.Open (Engine, Opened, Ready);

      if Ready then
         Products.Open_Sequence (Steps);
         Products.Add_Attention
           (Steps,
            Heads => Heads, Head_Size => Head_Size, Value_Size => Head_Size,
            Group_Size => 1, First => 0, Last => Positions - 1,
            K_Base => 0, V_Base => Natural (Room),
            KV_Width => Heads * Head_Size, V_Width => Heads * Head_Size,
            Scale => 0.25, Cap => 0.0, Added => Added);
         Assert (Added, "recording does not need a cache; running does");

         Products.Run (Engine, Steps, Query, 1, Recorded, Ok, Halted);
         Assert (not Ok,
                 "a sequence attending against a cache the engine does not "
                 & "hold was run rather than refused");
      end if;

      Products.Close (Engine);
      Devices.Close (Opened);
      Devices.Close (Held);
   end Recorded_Attention_Says_What_A_Call_Says;

   ---------------------------------------------
   -- Joined_Pair_Says_What_Two_Steps_Say --
   ---------------------------------------------

   --  Attention and its projection named together against the two done
   --  apart, on the same cache with the same queries and the same matrix.
   --
   --  What the joining is for is a submission and a round trip, not a
   --  different answer, so the answer has to be the same one. The saving is
   --  measured by `tests device-bench` and is not what this asserts.
   procedure Joined_Pair_Says_What_Two_Steps_Say
     (T_Case : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T_Case);

      Heads     : constant := 4;
      Head_Size : constant := 8;
      Positions : constant := 5;

      Span : constant N.Element_Count := Heads * Head_Size;
      Room : constant N.Element_Count :=
        N.Element_Count (Positions) * Span;

      Ready : Boolean;
      Ok    : Boolean;

      Cache : N.Real_Array (0 .. Room * 2 - 1);
      Query : N.Real_Array (0 .. Span - 1);

      Blend : T.Real_Array_Access;
      Apart : T.Real_Array_Access;
      Joint : T.Real_Array_Access;

      --  A square matrix of the width a blend has, so the projection reads
      --  the blend whole and writes something of the same size.
      Weights : Model_Runner.Bytes.Byte_Array_Access;
      Matrix  : T.View;

      Status : E.Error_Info;

      Near : constant N.Real := 1.0e-4;
   begin
      Model_Runner.Backend.Device.Close;
      Model_Runner.Backend.Device.Open (Ready, Share_Host => False);

      if not Ready then
         return;
      end if;

      for Index in Cache'Range loop
         Cache (Index) := N.Real (Index mod 13) / 13.0 - 0.5;
      end loop;
      for Index in Query'Range loop
         Query (Index) := N.Real (Index mod 7) / 7.0 - 0.25;
      end loop;

      T.Allocate (Span, Blend);
      T.Allocate (Span, Apart);
      T.Allocate (Span, Joint);
      Model_Runner.Bytes.Allocate
        (Model_Runner.Bytes.Byte_Count (Span * Span) * 4, Weights);

      Assert (Blend /= null and then Apart /= null and then Joint /= null
              and then Weights /= null, "no room for the test");

      --  Values with structure, written as bytes because that is how a
      --  matrix reaches a backend.
      for Row in 0 .. Span - 1 loop
         for Column in 0 .. Span - 1 loop
            declare
               Value : constant N.Real :=
                 N.Real ((Row + 2 * Column) mod 11) / 11.0 - 0.4;
               At_Byte : constant Model_Runner.Bytes.Byte_Count :=
                 Model_Runner.Bytes.Byte_Count (Row * Span + Column) * 4 + 1;
            begin
               Weights.all (At_Byte .. At_Byte + 3) :=
                 Model_Runner.Bytes.Put_F32 (Value);
            end;
         end loop;
      end loop;

      Matrix := (Format => Model_Runner.GGUF.Type_F32,
                 Rows => Span, Columns => Span,
                 Base => Weights.all'Address,
                 Span => Model_Runner.Bytes.Byte_Count (Weights.all'Length),
                 Offset => 0,
                 Length => Model_Runner.Bytes.Byte_Count
                             (Weights.all'Length));

      Model_Runner.Backend.Device.Reserve_Cache (Cache'Length, Ok);

      if not Ok then
         Model_Runner.Backend.Device.Close;
         return;
      end if;

      Model_Runner.Backend.Device.Put_Cache (0, Cache, Ok);
      Assert (Ok, "the cache would not be written");

      --  Apart: attend, bring the blend back, send it again as the
      --  projection's activation.
      Model_Runner.Backend.Device.Attend
        (Query, Heads, Head_Size, Head_Size, 1, 0, Positions - 1,
         0, Natural (Room), Heads * Head_Size, Heads * Head_Size,
         0.25, 0.0, Blend.all, Ok);
      Assert (Ok, "attention on its own was refused");

      Model_Runner.Backend.Device.Dispatch (Matrix, Blend, Apart, Status);
      Assert (not E.Is_Error (Status),
              "the projection on its own was refused");

      --  Together: one submission, and the blend never comes back.
      Model_Runner.Backend.Device.Attend_And_Project
        (Query, Heads, Head_Size, Head_Size, 1, 0, Positions - 1,
         0, Natural (Room), Heads * Head_Size, Heads * Head_Size,
         0.25, 0.0, Matrix, Joint, Ok);
      Assert (Ok, "the pair named together was refused");

      for Index in 0 .. Span - 1 loop
         Assert (abs (Apart.all (Index) - Joint.all (Index)) <= Near,
                 "the pair named together differs from the two done apart "
                 & "at component" & N.Element_Count'Image (Index));
      end loop;

      T.Free (Blend);
      T.Free (Apart);
      T.Free (Joint);
      Model_Runner.Bytes.Free (Weights);
      Model_Runner.Backend.Device.Close;
   end Joined_Pair_Says_What_Two_Steps_Say;

   ----------
   -- Name --
   ----------

   overriding function Name (T : Case_Type) return AUnit.Message_String is
      pragma Unreferenced (T);
   begin
      return AUnit.Format ("cpu backend");
   end Name;

   --------------------
   -- Register_Tests --
   --------------------

   ------------------------------------
   -- Cores_Are_Not_Above_Processors --
   ------------------------------------

   --  The default worker count follows the core count, so what that function
   --  may return is worth pinning even on a host whose answer this test
   --  cannot know.
   --
   --  It has one interesting failure: a host that describes its topology in a
   --  way the reading does not understand, which must produce the processor
   --  count rather than zero, a negative, or a number above it. Any of those
   --  would reach the pool as a worker count and either run serially without
   --  saying so or ask for more workers than the backend accepts.

   procedure Cores_Are_Not_Above_Processors
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Processors : constant Positive := Model_Runner.Platform.Processor_Count;
      Cores      : constant Positive := Model_Runner.Platform.Core_Count;
   begin
      Assert (Cores <= Processors,
              "core count" & Positive'Image (Cores)
              & " is above the processor count" & Positive'Image (Processors));

      --  Repeated because it reads the host each time rather than caching,
      --  and a reading that changed between calls would make the default
      --  depend on when it was asked.
      Assert (Model_Runner.Platform.Core_Count = Cores,
              "the core count changed between two readings");
   end Cores_Are_Not_Above_Processors;

   -------------------------------
   -- Shares_Cannot_Raise --
   -------------------------------

   --  Shared work covers every item exactly once, whatever the pool.
   --
   --  The pool cuts a count of items into shares the way it cuts the rows of
   --  a matrix, and what a caller needs of that is not speed but a promise:
   --  every item is done, none is done twice, and the answer does not depend
   --  on how many workers there were. Attention rests on it -- a head not
   --  blended is a head of zeros in the middle of an answer, and a head
   --  blended twice is one that has been added to its own output.
   --
   --  Marked per item rather than counted, so that an item done twice fails
   --  as loudly as one not done at all.
   procedure Shared_Work_Covers_Every_Item
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Items : constant N.Element_Count := 37;

      type Marks is array (N.Element_Count range 0 .. Items - 1) of Natural;

      type Counting is limited new CPU.Task_Item with record
         Seen : Marks := [others => 0];
      end record;

      overriding procedure Run
        (Item  : in out Counting;
         First : N.Element_Count;
         Last  : N.Element_Count);

      overriding procedure Run
        (Item  : in out Counting;
         First : N.Element_Count;
         Last  : N.Element_Count) is
      begin
         if First > Last then
            return;
         end if;

         for Index in First .. Last loop
            Item.Seen (Index) := Item.Seen (Index) + 1;
         end loop;
      end Run;

      Status : E.Error_Info;
   begin
      --  Serially, which is what a caller with no pool gets.
      declare
         Work : aliased Counting;
      begin
         CPU.Dispatch_Shares (null, Items, Work'Unchecked_Access, Status);
         Assert (E.Is_Ok (Status), "the serial path refused the work");

         for Index in Work.Seen'Range loop
            Assert (Work.Seen (Index) = 1,
                    "the serial path did item"
                    & N.Element_Count'Image (Index)
                    & Natural'Image (Work.Seen (Index)) & " times");
         end loop;
      end;

      --  And across every pool size this machine's bounds allow, since the
      --  partition's edges are where a cover stops covering.
      for Workers in CPU.Worker_Count range 1 .. 9 loop
         declare
            Team : aliased CPU.Pool (Workers);
            Work : aliased Counting;
         begin
            CPU.Dispatch_Shares
              (Team'Unchecked_Access, Items, Work'Unchecked_Access, Status);
            Assert (E.Is_Ok (Status),
                    "a pool of" & CPU.Worker_Count'Image (Workers)
                    & " refused the work");

            for Index in Work.Seen'Range loop
               Assert (Work.Seen (Index) = 1,
                       "a pool of" & CPU.Worker_Count'Image (Workers)
                       & " did item" & N.Element_Count'Image (Index)
                       & Natural'Image (Work.Seen (Index)) & " times");
            end loop;

            CPU.Close (Team);
         end;
      end loop;

      --  Nothing to do is not a failure, and asks nothing of the pool.
      declare
         Work : aliased Counting;
      begin
         CPU.Dispatch_Shares (null, 0, Work'Unchecked_Access, Status);
         Assert (E.Is_Ok (Status), "an empty job was refused");
         Assert (Work.Seen (0) = 0, "an empty job did something");
      end;
   end Shared_Work_Covers_Every_Item;

   --  What keeps a share from raising, held so that it stays true.
   --
   --  Both the worker and the task that submits a job run their share inside
   --  a handler that catches everything and reports a failure rather than
   --  letting the task die. Neither handler can be reached through this
   --  package: the range procedures check every shape they are given and
   --  return, so a caller that asks for something impossible gets nothing
   --  done rather than an exception. The handlers are a net for what nobody
   --  thought of, and a net is not a path.
   --
   --  That is a property of the guards in Mat_Mul_Range and Mat_Vec_Range,
   --  and this is what says so. If one of those guards is removed, a
   --  malformed request reaches the arithmetic, and this fails -- which is
   --  the warning that the handlers have become reachable and now need
   --  reaching in a test.

   procedure Shares_Cannot_Raise
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Data   : B.Byte_Array_Access;
      Item   : T.View;

      Vector : constant N.Real_Array (0 .. Columns - 1) := [others => 1.0];
      Target : N.Real_Array (0 .. Rows - 1) := [others => 0.0];

      Untouched : Boolean;

      --  Every shape the guards are there to refuse. A short output, a short
      --  input, no vectors at all, an empty range, and a last row past the
      --  end of the matrix.
      procedure Nothing_Happened (What : String) is
      begin
         Untouched := True;
         for Value of Target loop
            if Value /= 0.0 then
               Untouched := False;
            end if;
         end loop;
         Assert (Untouched,
                 "a malformed request wrote to the output: " & What);
      end Nothing_Happened;
   begin
      Make_Weight (Data, Item);

      declare
         Short_Target : N.Real_Array (0 .. Rows - 2) := [others => 0.0];
         Short_Vector : constant N.Real_Array (0 .. Columns - 2) :=
           [others => 1.0];
      begin
         T.Mat_Mul_Range (Item, Vector, 1, Short_Target, 0, Rows - 1);
         for Value of Short_Target loop
            Assert (Value = 0.0, "a short output was written to");
         end loop;

         T.Mat_Mul_Range (Item, Short_Vector, 1, Target, 0, Rows - 1);
         Nothing_Happened ("a short input");

         T.Mat_Mul_Range (Item, Vector, 0, Target, 0, Rows - 1);
         Nothing_Happened ("no vectors");

         T.Mat_Mul_Range (Item, Vector, 1, Target, 2, 1);
         Nothing_Happened ("an empty row range");

         T.Mat_Mul_Range (Item, Vector, 1, Target, 0, Rows);
         Nothing_Happened ("a last row past the end");

         T.Mat_Vec_Range (Item, Short_Vector, Target, 0, Rows - 1);
         Nothing_Happened ("a short input to the single-vector form");

         T.Mat_Vec_Range (Item, Vector, Target, 0, Rows);
         Nothing_Happened ("a last row past the end, single vector");
      end;

      --  And the shape that is not malformed still works, so that the checks
      --  above are not passing because nothing works at all.
      T.Mat_Vec_Range (Item, Vector, Target, 0, Rows - 1);
      Untouched := True;
      for Value of Target loop
         if Value /= 0.0 then
            Untouched := False;
         end if;
      end loop;
      Assert (not Untouched,
              "a well-formed request wrote nothing, so the checks above "
              & "prove nothing");

      B.Free (Data);
   end Shares_Cannot_Raise;

   -----------------------------------
   -- Default_Team_Leaves_A_Share --
   -----------------------------------

   --  What the command line opens a pool with when nobody says.
   --
   --  The number itself is not the point; the relation is. A job is cut into
   --  one more share than the pool has workers, so what has to fit on the
   --  machine is the workers plus one, and a default that forgets the plus
   --  one puts a runnable task on every core and then one more. That is
   --  measurably slower, and it is the kind of arithmetic that is corrected
   --  once and quietly undone later.

   procedure Default_Team_Leaves_A_Share
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      --  The whole point, for every machine size above the two-core case.
      for Cores in 3 .. 256 loop
         declare
            Workers : constant Positive :=
              Positive (CPU.Default_Workers (Cores));
            Shares  : constant Positive := Workers + 1;
         begin
            Assert (Shares <= Cores
                    or else Workers = CPU.Max_Workers,
                    "on" & Integer'Image (Cores) & " cores the default asks"
                    & " for" & Integer'Image (Workers) & " workers, which is"
                    & Integer'Image (Shares) & " shares");
         end;
      end loop;

      --  And it does not leave more than one core idle either, which a
      --  cores-minus-two would.
      for Cores in 3 .. 64 loop
         Assert (Positive (CPU.Default_Workers (Cores)) + 1 = Cores,
                 "on" & Integer'Image (Cores) & " cores the default leaves"
                 & " more than the submitting task's share idle");
      end loop;

      --  One core is serial, and two are both used rather than becoming one
      --  worker, which the command line would run serially.
      Assert (Positive (CPU.Default_Workers (1)) = 1,
              "one core did not give one worker");
      Assert (Positive (CPU.Default_Workers (2)) = 2,
              "two cores did not give two workers");

      --  A machine larger than the pool allows is capped rather than
      --  refused, since the result is a worker count and has to be one.
      Assert (Positive (CPU.Default_Workers (10_000)) = CPU.Max_Workers,
              "a machine larger than the pool allows was not capped");
   end Default_Team_Leaves_A_Share;

   overriding procedure Register_Tests (T : in out Case_Type) is
      use AUnit.Test_Cases.Registration;
   begin
      Register_Routine
        (T, Partition_Covers_Rows'Access,
         "the partition covers every row exactly once for every worker count");
      Register_Routine
        (T, Parallel_Matches_Serial'Access,
         "a parallel product equals the serial one exactly");
      Register_Routine
        (T, More_Workers_Than_Rows'Access,
         "more workers than rows still produces a complete result");
      Register_Routine
        (T, Closed_Pool_Rejects'Access,
         "a closed pool rejects work and closing twice is harmless");
      Register_Routine
        (T, Pool_Is_Reused'Access,
         "one pool serves many jobs without creating tasks per job");
      Register_Routine
        (T, Unused_Pool_Terminates'Access,
         "a pool that is never used still terminates");
      Register_Routine
        (T, Capabilities_Reported'Access,
         "capabilities report only what the backend implements");
      Register_Routine
        (T, Device_Reports_What_It_Reads'Access,
         "the device backend claims the formats its shader decodes and no "
         & "others");
      Register_Routine
        (T, Device_Reads_The_Host_Memory_When_Asked'Access,
         "a device asked to read the weights where they lie gives the same "
         & "answers as one handed a copy");
      Register_Routine
        (T, Device_Decodes_Every_Format_It_Claims'Access,
         "the device decodes every format it claims, as the processor does");
      AUnit.Test_Cases.Registration.Register_Routine
        (T, Device_Gives_Up_On_One_That_Will_Not_Answer'Access,
         "a dispatch that outlasts the whole bound finishes the engine");
      AUnit.Test_Cases.Registration.Register_Routine
        (T, Device_Stops_When_The_Caller_Asks'Access,
         "a product on the device answers a standing stop request");
      AUnit.Test_Cases.Registration.Register_Routine
        (T, Device_Gives_Back_What_It_Cannot_Hold'Access,
         "a device with less memory than the matrices need gives back the "
         & "one wanted longest ago and keeps computing");
      Register_Routine
        (T, Device_Refuses_What_It_Must'Access,
         "the device backend refuses no device, a format it cannot read, "
         & "and shapes that are not products");

      Register_Routine
        (T, Cores_Are_Not_Above_Processors'Access,
         "the core count is at least one and never above the processor "
         & "count, whatever the host reports");
      Register_Routine
        (T, Shares_Cannot_Raise'Access,
         "a malformed request is refused by the range procedures rather "
         & "than raising, which is what makes the failure handlers a net "
         & "and not a path");
      Register_Routine
        (T, Default_Team_Leaves_A_Share'Access,
         "the default worker count leaves a share for the task that submits "
         & "the job, on every machine size");
      Register_Routine
        (T, Resident_Cache_Attends_As_A_Host_Does'Access,
         "a cache a device holds is written and attended to, and says what "
         & "a blend worked out by hand says");
      Register_Routine
        (T, Recorded_Attention_Says_What_A_Call_Says'Access,
         "attention recorded into a sequence says what attention submitted "
         & "on its own says, and a sequence attending against a cache that "
         & "is not there is refused");
      Register_Routine
        (T, Shared_Work_Covers_Every_Item'Access,
         "work shared across the pool covers every item exactly once, "
         & "whatever the worker count");
      Register_Routine
        (T, Joined_Pair_Says_What_Two_Steps_Say'Access,
         "attention and its projection named together say what the two "
         & "done apart say");
   end Register_Tests;

end Tests.Backend_Cases;
