with AUnit.Assertions;

with Model_Runner.Backend;
with Model_Runner.Backend.CPU;
with Model_Runner.Bytes;
with Model_Runner.Errors;
with Model_Runner.GGUF;
with Model_Runner.Numerics;
with Model_Runner.Platform;
with Model_Runner.Tensors;

with Fixtures;

package body Tests.Backend_Cases is

   use AUnit.Assertions;
   use type Model_Runner.Bytes.Byte_Array_Access;
   use type Model_Runner.Errors.Error_Code;
   use type Model_Runner.Numerics.Element_Count;
   use type Model_Runner.Numerics.Real;
   use type Model_Runner.Tensors.Real_Array_Access;

   package B renames Model_Runner.Bytes;
   package CPU renames Model_Runner.Backend.CPU;
   package E renames Model_Runner.Errors;
   package G renames Model_Runner.GGUF;
   package N renames Model_Runner.Numerics;
   package T renames Model_Runner.Tensors;

   Rows    : constant N.Element_Count := 37;
   Columns : constant N.Element_Count := 24;

   --  Build a float32 weight view over freshly generated bytes.
   procedure Make_Weight
     (Storage : out B.Byte_Array_Access;
      Weight  : out T.View)
   is
      Values : constant N.Real_Array :=
        Fixtures.Sequence (Rows * Columns, 4321, 1.0);
      Bytes  : constant B.Byte_Array := Fixtures.Encode_F32 (Values);
      Status : E.Error_Info;
   begin
      B.Allocate (Bytes'Length, Storage);
      Storage.all := Bytes;
      T.Make (G.Type_F32, Rows, Columns, Storage, 0, Weight, Status);
      Assert (E.Is_Ok (Status), "weight view could not be built");
   end Make_Weight;

   --  The partition covers every row exactly once, for every worker count.
   procedure Partition_Covers_Rows (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      for Total in N.Element_Count range 0 .. 40 loop
         --  Share counts, not worker counts: a job is cut into one more
         --  piece than there are workers, because the submitting task takes
         --  one. The top of that range is one past the top of this one.
         for Team in CPU.Share_Count range 1 .. 9 loop
            declare
               Seen : array (N.Element_Count range 0 .. 40) of Natural :=
                 [others => 0];
            begin
               for Index in CPU.Share_Count range 1 .. Team loop
                  declare
                     First, Last : N.Element_Count;
                  begin
                     CPU.Partition (Total, Team, Index, First, Last);
                     if First <= Last then
                        Assert (Last < Total,
                                "partition ran past the last row");
                        for Row in First .. Last loop
                           Seen (Row) := Seen (Row) + 1;
                        end loop;
                     end if;
                  end;
               end loop;

               for Row in N.Element_Count range 0 .. Total - 1 loop
                  Assert (Seen (Row) = 1,
                          "row" & N.Element_Count'Image (Row)
                          & " was covered" & Natural'Image (Seen (Row))
                          & " times with" & CPU.Share_Count'Image (Team)
                          & " workers");
               end loop;
            end;
         end loop;
      end loop;

      --  The largest share count there is, which is one past the largest
      --  worker count and is reached whenever a pool is opened with the
      --  maximum number of workers. Nothing else in this file goes near it.
      declare
         Total : constant N.Element_Count := 200;
         Seen  : array (0 .. 199) of Natural := [others => 0];
         First, Last : N.Element_Count;
      begin
         for Index in CPU.Share_Count'Range loop
            CPU.Partition (Total, CPU.Share_Count'Last, Index, First, Last);
            if First <= Last then
               for Row in First .. Last loop
                  Seen (Natural (Row)) := Seen (Natural (Row)) + 1;
               end loop;
            end if;
         end loop;

         for Row in Seen'Range loop
            Assert (Seen (Row) = 1,
                    "row" & Natural'Image (Row) & " covered"
                    & Natural'Image (Seen (Row)) & " times with"
                    & CPU.Share_Count'Image (CPU.Share_Count'Last)
                    & " shares");
         end loop;
      end;

   end Partition_Covers_Rows;

   --  A parallel product equals the serial one exactly, for every worker
   --  count. This is the property that makes changing --threads safe.
   procedure Parallel_Matches_Serial
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Status  : E.Error_Info;
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);

      declare
         Input : constant N.Real_Array := Fixtures.Sequence (Columns, 99, 1.0);
      begin
         Vector.all := Input;
      end;

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      for Team in CPU.Worker_Count range 1 .. 6 loop
         declare
            Pool     : aliased CPU.Pool (Team);
            Parallel : T.Real_Array_Access;
         begin
            T.Allocate (Rows, Parallel);
            CPU.Open (Pool);
            Assert (CPU.Is_Open (Pool), "pool did not open");
            Assert (CPU.Worker_Total (Pool) = Team, "wrong worker count");

            CPU.Mat_Vec (Pool, Weight, Vector, Parallel, Status);
            Assert (E.Is_Ok (Status),
                    "parallel product failed with"
                    & CPU.Worker_Count'Image (Team) & " workers: "
                    & E.Error_Code'Image (Status.Code));

            for Row in 0 .. Rows - 1 loop
               Assert (Parallel.all (Row) = Serial.all (Row),
                       "row" & N.Element_Count'Image (Row)
                       & " differs with" & CPU.Worker_Count'Image (Team)
                       & " workers");
            end loop;

            CPU.Close (Pool);
            T.Free (Parallel);
         end;
      end loop;

      T.Free (Vector);
      T.Free (Serial);
      B.Free (Storage);
   end Parallel_Matches_Serial;

   --  More workers than rows is legal: the surplus workers get nothing and the
   --  result is still complete.
   procedure More_Workers_Than_Rows
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Wide    : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (CPU.Worker_Count (Rows + 5));
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);
      T.Allocate (Rows, Wide);
      Vector.all := Fixtures.Sequence (Columns, 99, 1.0);

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      CPU.Mat_Vec (Pool, Weight, Vector, Wide, Status);
      Assert (E.Is_Ok (Status), "oversized pool failed");

      for Row in 0 .. Rows - 1 loop
         Assert (Wide.all (Row) = Serial.all (Row),
                 "row" & N.Element_Count'Image (Row)
                 & " differs when workers outnumber rows");
      end loop;

      CPU.Close (Pool);
      T.Free (Vector);
      T.Free (Serial);
      T.Free (Wide);
      B.Free (Storage);
   end More_Workers_Than_Rows;

   --  A closed pool rejects work rather than queueing it, and closing twice is
   --  harmless.
   procedure Closed_Pool_Rejects (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Target  : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (3);
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Target);
      Vector.all := Fixtures.Sequence (Columns, 5, 1.0);

      CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
      Assert (E.Is_Ok (Status), "first product failed");

      CPU.Close (Pool);
      Assert (not CPU.Is_Open (Pool), "a closed pool reported itself open");

      CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
      Assert (Status.Code = E.Backend_Closed,
              "a closed pool accepted work: " & E.Error_Code'Image (Status.Code));

      --  Closing twice must be harmless.
      CPU.Close (Pool);
      Assert (not CPU.Is_Open (Pool), "a second close changed the state");

      T.Free (Vector);
      T.Free (Target);
      B.Free (Storage);
   end Closed_Pool_Rejects;

   --  A pool is reusable: many jobs run through the same workers, and no task
   --  is created per job.
   procedure Pool_Is_Reused (T2 : in out AUnit.Test_Cases.Test_Case'Class) is
      pragma Unreferenced (T2);
      Storage : B.Byte_Array_Access;
      Weight  : T.View;
      Vector  : T.Real_Array_Access;
      Serial  : T.Real_Array_Access;
      Target  : T.Real_Array_Access;
      Status  : E.Error_Info;
      Pool    : aliased CPU.Pool (4);
   begin
      Make_Weight (Storage, Weight);
      T.Allocate (Columns, Vector);
      T.Allocate (Rows, Serial);
      T.Allocate (Rows, Target);
      Vector.all := Fixtures.Sequence (Columns, 17, 1.0);

      CPU.Dispatch (null, Weight, Vector, Serial, Status);
      Assert (E.Is_Ok (Status), "serial product failed");

      for Round in 1 .. 50 loop
         Target.all := [others => 0.0];
         CPU.Mat_Vec (Pool, Weight, Vector, Target, Status);
         Assert (E.Is_Ok (Status),
                 "round" & Integer'Image (Round) & " failed");
         for Row in 0 .. Rows - 1 loop
            Assert (Target.all (Row) = Serial.all (Row),
                    "round" & Integer'Image (Round) & " differed");
         end loop;
      end loop;

      CPU.Close (Pool);
      T.Free (Vector);
      T.Free (Serial);
      T.Free (Target);
      B.Free (Storage);
   end Pool_Is_Reused;

   --  A pool that is created and then never used must still terminate. It
   --  does not, if its workers are left waiting for the call that binds them:
   --  the frame that declared the pool would wait for them forever. This test
   --  hangs rather than fails when that regresses, which is the only way the
   --  condition can be observed.
   procedure Unused_Pool_Terminates
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      for Team in CPU.Worker_Count range 1 .. 4 loop
         declare
            Idle : CPU.Pool (Team);
         begin
            --  Deliberately no work and no Open: this is the shape a command
            --  that fails while loading its model leaves behind.
            Assert (CPU.Worker_Total (Idle) = Team, "wrong worker count");
         end;
      end loop;

      --  A pool that is closed without ever running work must also terminate.
      declare
         Idle : CPU.Pool (3);
      begin
         CPU.Close (Idle);
         Assert (not CPU.Is_Open (Idle), "a closed pool reported itself open");
      end;
   end Unused_Pool_Terminates;

   --  Capabilities report what the backend actually implements.
   procedure Capabilities_Reported (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Single : constant Model_Runner.Backend.Capabilities := CPU.Describe (1);
      Many   : constant Model_Runner.Backend.Capabilities := CPU.Describe (4);
   begin
      Assert (Model_Runner.Backend.Backend_Name (Single.Kind) = "cpu",
              "wrong backend name");
      --  Determinism was a field here and is not any more: it could only
      --  ever be True, and a flag with one value documents nothing. What it
      --  claimed is tested where it can fail, by generating the same text at
      --  one worker and at four.
      Assert (not Single.Supports_Parallel,
              "one worker was reported as parallel");
      Assert (Many.Supports_Parallel, "many workers were reported as serial");
      Assert (Many.Max_Workers = CPU.Max_Workers, "wrong worker maximum");

      --  Only the formats with a decoder are advertised.
      Assert (Model_Runner.Backend.Supports (Single, G.Type_F32), "F32");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q4_K), "Q4_K");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q6_K), "Q6_K");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_Q2_K),
              "Q2_K is implemented but not advertised");
      Assert (Model_Runner.Backend.Supports (Single, G.Type_BF16),
              "BF16 is implemented but not advertised");
   end Capabilities_Reported;

   ----------
   -- Name --
   ----------

   overriding function Name (T : Case_Type) return AUnit.Message_String is
      pragma Unreferenced (T);
   begin
      return AUnit.Format ("cpu backend");
   end Name;

   --------------------
   -- Register_Tests --
   --------------------

   ------------------------------------
   -- Cores_Are_Not_Above_Processors --
   ------------------------------------

   --  The default worker count follows the core count, so what that function
   --  may return is worth pinning even on a host whose answer this test
   --  cannot know.
   --
   --  It has one interesting failure: a host that describes its topology in a
   --  way the reading does not understand, which must produce the processor
   --  count rather than zero, a negative, or a number above it. Any of those
   --  would reach the pool as a worker count and either run serially without
   --  saying so or ask for more workers than the backend accepts.

   procedure Cores_Are_Not_Above_Processors
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
      Processors : constant Positive := Model_Runner.Platform.Processor_Count;
      Cores      : constant Positive := Model_Runner.Platform.Core_Count;
   begin
      Assert (Cores <= Processors,
              "core count" & Positive'Image (Cores)
              & " is above the processor count" & Positive'Image (Processors));

      --  Repeated because it reads the host each time rather than caching,
      --  and a reading that changed between calls would make the default
      --  depend on when it was asked.
      Assert (Model_Runner.Platform.Core_Count = Cores,
              "the core count changed between two readings");
   end Cores_Are_Not_Above_Processors;

   -------------------------------
   -- Shares_Cannot_Raise --
   -------------------------------

   --  What keeps a share from raising, held so that it stays true.
   --
   --  Both the worker and the task that submits a job run their share inside
   --  a handler that catches everything and reports a failure rather than
   --  letting the task die. Neither handler can be reached through this
   --  package: the range procedures check every shape they are given and
   --  return, so a caller that asks for something impossible gets nothing
   --  done rather than an exception. The handlers are a net for what nobody
   --  thought of, and a net is not a path.
   --
   --  That is a property of the guards in Mat_Mul_Range and Mat_Vec_Range,
   --  and this is what says so. If one of those guards is removed, a
   --  malformed request reaches the arithmetic, and this fails -- which is
   --  the warning that the handlers have become reachable and now need
   --  reaching in a test.

   procedure Shares_Cannot_Raise
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);

      Data   : B.Byte_Array_Access;
      Item   : T.View;

      Vector : constant N.Real_Array (0 .. Columns - 1) := [others => 1.0];
      Target : N.Real_Array (0 .. Rows - 1) := [others => 0.0];

      Untouched : Boolean;

      --  Every shape the guards are there to refuse. A short output, a short
      --  input, no vectors at all, an empty range, and a last row past the
      --  end of the matrix.
      procedure Nothing_Happened (What : String) is
      begin
         Untouched := True;
         for Value of Target loop
            if Value /= 0.0 then
               Untouched := False;
            end if;
         end loop;
         Assert (Untouched,
                 "a malformed request wrote to the output: " & What);
      end Nothing_Happened;
   begin
      Make_Weight (Data, Item);

      declare
         Short_Target : N.Real_Array (0 .. Rows - 2) := [others => 0.0];
         Short_Vector : constant N.Real_Array (0 .. Columns - 2) :=
           [others => 1.0];
      begin
         T.Mat_Mul_Range (Item, Vector, 1, Short_Target, 0, Rows - 1);
         for Value of Short_Target loop
            Assert (Value = 0.0, "a short output was written to");
         end loop;

         T.Mat_Mul_Range (Item, Short_Vector, 1, Target, 0, Rows - 1);
         Nothing_Happened ("a short input");

         T.Mat_Mul_Range (Item, Vector, 0, Target, 0, Rows - 1);
         Nothing_Happened ("no vectors");

         T.Mat_Mul_Range (Item, Vector, 1, Target, 2, 1);
         Nothing_Happened ("an empty row range");

         T.Mat_Mul_Range (Item, Vector, 1, Target, 0, Rows);
         Nothing_Happened ("a last row past the end");

         T.Mat_Vec_Range (Item, Short_Vector, Target, 0, Rows - 1);
         Nothing_Happened ("a short input to the single-vector form");

         T.Mat_Vec_Range (Item, Vector, Target, 0, Rows);
         Nothing_Happened ("a last row past the end, single vector");
      end;

      --  And the shape that is not malformed still works, so that the checks
      --  above are not passing because nothing works at all.
      T.Mat_Vec_Range (Item, Vector, Target, 0, Rows - 1);
      Untouched := True;
      for Value of Target loop
         if Value /= 0.0 then
            Untouched := False;
         end if;
      end loop;
      Assert (not Untouched,
              "a well-formed request wrote nothing, so the checks above "
              & "prove nothing");

      B.Free (Data);
   end Shares_Cannot_Raise;

   -----------------------------------
   -- Default_Team_Leaves_A_Share --
   -----------------------------------

   --  What the command line opens a pool with when nobody says.
   --
   --  The number itself is not the point; the relation is. A job is cut into
   --  one more share than the pool has workers, so what has to fit on the
   --  machine is the workers plus one, and a default that forgets the plus
   --  one puts a runnable task on every core and then one more. That is
   --  measurably slower, and it is the kind of arithmetic that is corrected
   --  once and quietly undone later.

   procedure Default_Team_Leaves_A_Share
     (T2 : in out AUnit.Test_Cases.Test_Case'Class)
   is
      pragma Unreferenced (T2);
   begin
      --  The whole point, for every machine size above the two-core case.
      for Cores in 3 .. 256 loop
         declare
            Workers : constant Positive :=
              Positive (CPU.Default_Workers (Cores));
            Shares  : constant Positive := Workers + 1;
         begin
            Assert (Shares <= Cores
                    or else Workers = CPU.Max_Workers,
                    "on" & Integer'Image (Cores) & " cores the default asks"
                    & " for" & Integer'Image (Workers) & " workers, which is"
                    & Integer'Image (Shares) & " shares");
         end;
      end loop;

      --  And it does not leave more than one core idle either, which a
      --  cores-minus-two would.
      for Cores in 3 .. 64 loop
         Assert (Positive (CPU.Default_Workers (Cores)) + 1 = Cores,
                 "on" & Integer'Image (Cores) & " cores the default leaves"
                 & " more than the submitting task's share idle");
      end loop;

      --  One core is serial, and two are both used rather than becoming one
      --  worker, which the command line would run serially.
      Assert (Positive (CPU.Default_Workers (1)) = 1,
              "one core did not give one worker");
      Assert (Positive (CPU.Default_Workers (2)) = 2,
              "two cores did not give two workers");

      --  A machine larger than the pool allows is capped rather than
      --  refused, since the result is a worker count and has to be one.
      Assert (Positive (CPU.Default_Workers (10_000)) = CPU.Max_Workers,
              "a machine larger than the pool allows was not capped");
   end Default_Team_Leaves_A_Share;

   overriding procedure Register_Tests (T : in out Case_Type) is
      use AUnit.Test_Cases.Registration;
   begin
      Register_Routine
        (T, Partition_Covers_Rows'Access,
         "the partition covers every row exactly once for every worker count");
      Register_Routine
        (T, Parallel_Matches_Serial'Access,
         "a parallel product equals the serial one exactly");
      Register_Routine
        (T, More_Workers_Than_Rows'Access,
         "more workers than rows still produces a complete result");
      Register_Routine
        (T, Closed_Pool_Rejects'Access,
         "a closed pool rejects work and closing twice is harmless");
      Register_Routine
        (T, Pool_Is_Reused'Access,
         "one pool serves many jobs without creating tasks per job");
      Register_Routine
        (T, Unused_Pool_Terminates'Access,
         "a pool that is never used still terminates");
      Register_Routine
        (T, Capabilities_Reported'Access,
         "capabilities report only what the backend implements");

      Register_Routine
        (T, Cores_Are_Not_Above_Processors'Access,
         "the core count is at least one and never above the processor "
         & "count, whatever the host reports");
      Register_Routine
        (T, Shares_Cannot_Raise'Access,
         "a malformed request is refused by the range procedures rather "
         & "than raising, which is what makes the failure handlers a net "
         & "and not a path");
      Register_Routine
        (T, Default_Team_Leaves_A_Share'Access,
         "the default worker count leaves a share for the task that submits "
         & "the job, on every machine size");
   end Register_Tests;

end Tests.Backend_Cases;
